import Papers.AnsariRockel2026RhoFootrule.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockel2026RhoFootrule.moment_representation
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.moment_representation

#print axioms Papers.AnsariRockel2026RhoFootrule.quadratic_upper_bound
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.quadratic_upper_bound

#print axioms Papers.AnsariRockel2026RhoFootrule.fixed_footrule_intermediate
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.fixed_footrule_intermediate
