import Papers.AnsariRockel2026RhoFootrule.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockel2026RhoFootrule.moment_representation
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.moment_representation

#print axioms Papers.AnsariRockel2026RhoFootrule.quadratic_upper_bound
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.quadratic_upper_bound

#print axioms Papers.AnsariRockel2026RhoFootrule.fixed_footrule_intermediate
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.fixed_footrule_intermediate

#print axioms Papers.AnsariRockel2026RhoFootrule.quadratic_defect
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.quadratic_defect

#print axioms Papers.AnsariRockel2026RhoFootrule.quadratic_equality_iff
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.quadratic_equality_iff

#print axioms Papers.AnsariRockel2026RhoFootrule.halfTurn_rho
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.halfTurn_rho

#print axioms Papers.AnsariRockel2026RhoFootrule.halfTurn_footrule
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.halfTurn_footrule

#print axioms Papers.AnsariRockel2026RhoFootrule.contactCopula_coefficients
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.contactCopula_coefficients

#print axioms Papers.AnsariRockel2026RhoFootrule.contactCopula_maximizes_rho
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.contactCopula_maximizes_rho

#print axioms Papers.AnsariRockel2026RhoFootrule.contactCopula_constant_displacement
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.contactCopula_constant_displacement

#print axioms Papers.AnsariRockel2026RhoFootrule.upperRho_parameter
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.upperRho_parameter

#print axioms Papers.AnsariRockel2026RhoFootrule.boundary_coefficients
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.boundary_coefficients

#print axioms Papers.AnsariRockel2026RhoFootrule.sharp_upper_bound
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.sharp_upper_bound

#print axioms Papers.AnsariRockel2026RhoFootrule.upper_boundary_attained
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.upper_boundary_attained

#print axioms Papers.AnsariRockel2026RhoFootrule.sharp_lower_bound
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.sharp_lower_bound

#print axioms Papers.AnsariRockel2026RhoFootrule.lower_boundary_attained
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.lower_boundary_attained

#print axioms Papers.AnsariRockel2026RhoFootrule.exact_region
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.exact_region

#print axioms Papers.AnsariRockel2026RhoFootrule.boundary_value_unique
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.boundary_value_unique

#print axioms Papers.AnsariRockel2026RhoFootrule.right_boundary_closed
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.right_boundary_closed

#print axioms Papers.AnsariRockel2026RhoFootrule.left_boundary_closed
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.left_boundary_closed

#print axioms Papers.AnsariRockel2026RhoFootrule.sharp_second_moment
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.sharp_second_moment

#print axioms Papers.AnsariRockel2026RhoFootrule.minimum_variance_attained
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.minimum_variance_attained

#print axioms Papers.AnsariRockel2026RhoFootrule.minimum_variance_nonneg
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.minimum_variance_nonneg

#print axioms Papers.AnsariRockel2026RhoFootrule.right_variance_closed
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.right_variance_closed

#print axioms Papers.AnsariRockel2026RhoFootrule.left_variance_closed
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.left_variance_closed

#print axioms Papers.AnsariRockel2026RhoFootrule.minimum_variance_zero_iff
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.minimum_variance_zero_iff

#print axioms Papers.AnsariRockel2026RhoFootrule.constant_displacement_iff
#assert_standard_axioms Papers.AnsariRockel2026RhoFootrule.constant_displacement_iff
