import Papers.AnsariRockel2026RhoFootrule.EarlierCurve
import Papers.AnsariRockel2026RhoFootrule.AsymptoticRankings
import Papers.AnsariRockel2026RhoFootrule.DiscreteEquality
import Papers.AnsariRockel2026RhoFootrule.UpperLocalizedCurves
import Papers.AnsariRockel2026RhoFootrule.UpperSeedsCompact
import Papers.AnsariRockel2026RhoFootrule.UpperSeedsProjection
import Papers.AnsariRockel2026RhoFootrule.UpperInnerEnvelope
import Papers.AnsariRockel2026RhoFootrule.LowerInnerCurve
import Papers.AnsariRockel2026RhoFootrule.InnerConvexity
import Papers.AnsariRockel2026RhoFootrule.UpperBinaryCurve
import Papers.AnsariRockel2026RhoFootrule.FoldedExample
import Papers.AnsariRockel2026RhoFootrule.QuantitativeRatio
import Papers.AnsariRockel2026RhoFootrule.MeanVariance
import Papers.AnsariRockel2026RhoFootrule.VarianceMaximum
import Papers.AnsariRockel2026RhoFootrule.FiniteRankings
import Papers.AnsariRockel2026RhoFootrule.CorrelationRatio
import Papers.AnsariRockel2026RhoFootrule.Mixability
import Papers.AnsariRockel2026RhoFootrule.Dispersion
import Papers.AnsariRockel2026RhoFootrule.BoundaryFormula
import Papers.AnsariRockel2026RhoFootrule.ExactRegion
import Papers.AnsariRockel2026RhoFootrule.Touchpoints
import Papers.AnsariRockel2026RhoFootrule.Moments

/-! # AnsariRockel2026RhoFootrule: public results

See `COVERAGE.md` for the exact verified subset and remaining obligations.
-/
