import Papers.OrendayLaresRockel2026TauFootruleBeta.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.concordance_mixture
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.concordance_mixture

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_mixture_continuous
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_mixture_continuous

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.fixed_footrule_beta_intermediate
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.fixed_footrule_beta_intermediate

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_cdf
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_cdf

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_zero
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_zero

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_one
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_one

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_tau
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_tau

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_footrule
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_footrule

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_beta

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.diagonal_le_centralW
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.diagonal_le_centralW

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaUpper_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaUpper_beta

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaUpper_footrule
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaUpper_footrule

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footrule_le_beta_upper
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footrule_le_beta_upper

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.maximal_footrule_at_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.maximal_footrule_at_beta

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.diagonal_beta_lower
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.diagonal_beta_lower

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.beta_lower_le_footrule
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.beta_lower_le_footrule

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.lowerSeed_coefficients
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.lowerSeed_coefficients

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaLower_coefficients
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaLower_coefficients

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.minimal_footrule_at_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.minimal_footrule_at_beta

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.exact_footrule_beta_region
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.exact_footrule_beta_region

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_footrule_bounds
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_footrule_bounds

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.upperTauSeed_coefficients
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.upperTauSeed_coefficients

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centered_tau_endpoints
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centered_tau_endpoints

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.exact_tau_footrule_region
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.exact_tau_footrule_region

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_beta_bounds
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_beta_bounds

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.exact_tau_beta_region
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.exact_tau_beta_region

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.joint_region_outer_bound
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.joint_region_outer_bound

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.lower_joint_face_attained
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.lower_joint_face_attained
