import Papers.OrendayLaresRockel2026TauFootruleBeta.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.concordance_mixture
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.concordance_mixture

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_mixture_continuous
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_mixture_continuous

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.fixed_footrule_beta_intermediate
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.fixed_footrule_beta_intermediate

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_cdf
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_cdf

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_zero
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_zero

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_one
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_one

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_tau
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_tau

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_footrule
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_footrule

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.centeredOrdinal_beta

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.diagonal_le_centralW
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.diagonal_le_centralW

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaUpper_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaUpper_beta

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaUpper_footrule
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footruleBetaUpper_footrule

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footrule_le_beta_upper
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.footrule_le_beta_upper

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.maximal_footrule_at_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.maximal_footrule_at_beta
