import Papers.OrendayLaresRockel2026TauFootruleBeta.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.concordance_mixture
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.concordance_mixture

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_mixture_continuous
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.tau_mixture_continuous

#print axioms Papers.OrendayLaresRockel2026TauFootruleBeta.fixed_footrule_beta_intermediate
#assert_standard_axioms Papers.OrendayLaresRockel2026TauFootruleBeta.fixed_footrule_beta_intermediate
