import Papers.OrendayLaresRockel2026TauFootruleBeta.ShuffleFormula
import Papers.OrendayLaresRockel2026TauFootruleBeta.JointVolume
import Papers.OrendayLaresRockel2026TauFootruleBeta.FootruleBetaLower
import Papers.OrendayLaresRockel2026TauFootruleBeta.PairwiseRegions
import Papers.OrendayLaresRockel2026TauFootruleBeta.LowerJointFace
import Papers.OrendayLaresRockel2026TauFootruleBeta.FootruleBeta
import Papers.OrendayLaresRockel2026TauFootruleBeta.Mixtures
import Papers.OrendayLaresRockel2026TauFootruleBeta.CenteredOrdinal

/-! # OrendayLaresRockel2026TauFootruleBeta: public results

See `COVERAGE.md` for the exact statements, conventions and source correspondence.
-/
