import Papers.OrendayLaresRockel2026XiBeta.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.OrendayLaresRockel2026XiBeta.xi_derivative_formula
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.xi_derivative_formula

#print axioms Papers.OrendayLaresRockel2026XiBeta.xi_mixture_continuous
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.xi_mixture_continuous

#print axioms Papers.OrendayLaresRockel2026XiBeta.beta_mixture_fixed
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.beta_mixture_fixed

#print axioms Papers.OrendayLaresRockel2026XiBeta.fixed_beta_intermediate
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.fixed_beta_intermediate
