import Papers.OrendayLaresRockel2026XiBeta.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.OrendayLaresRockel2026XiBeta.xi_derivative_formula
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.xi_derivative_formula

#print axioms Papers.OrendayLaresRockel2026XiBeta.xi_mixture_continuous
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.xi_mixture_continuous

#print axioms Papers.OrendayLaresRockel2026XiBeta.beta_mixture_fixed
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.beta_mixture_fixed

#print axioms Papers.OrendayLaresRockel2026XiBeta.fixed_beta_intermediate
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.fixed_beta_intermediate

#print axioms Papers.OrendayLaresRockel2026XiBeta.medianDisplacement_lipschitz
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.medianDisplacement_lipschitz

#print axioms Papers.OrendayLaresRockel2026XiBeta.median_strip_energy
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.median_strip_energy

#print axioms Papers.OrendayLaresRockel2026XiBeta.median_energy_le_xi
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.median_energy_le_xi

#print axioms Papers.OrendayLaresRockel2026XiBeta.medianTent_le_abs_displacement
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.medianTent_le_abs_displacement

#print axioms Papers.OrendayLaresRockel2026XiBeta.beta_cubic_le_two_xi
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.beta_cubic_le_two_xi

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_cdf
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_cdf

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_beta

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_xi
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_xi

#print axioms Papers.OrendayLaresRockel2026XiBeta.left_boundary_attained
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.left_boundary_attained

#print axioms Papers.OrendayLaresRockel2026XiBeta.xi_eq_lower_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.xi_eq_lower_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.xi_twoBlockFlip
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.xi_twoBlockFlip

#print axioms Papers.OrendayLaresRockel2026XiBeta.rightBoundary_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.rightBoundary_beta

#print axioms Papers.OrendayLaresRockel2026XiBeta.rightBoundary_xi
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.rightBoundary_xi

#print axioms Papers.OrendayLaresRockel2026XiBeta.right_boundary_attained
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.right_boundary_attained

#print axioms Papers.OrendayLaresRockel2026XiBeta.exact_xi_beta_region
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.exact_xi_beta_region

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_conditionalCDF
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_conditionalCDF

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_quadrant_masses
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_quadrant_masses

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_reflect_first
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_reflect_first

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_reflect_second
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_reflect_second

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_radiallySymmetric
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_radiallySymmetric

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_zero
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_zero

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_si_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_si_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_sd_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_sd_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_pqd_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_pqd_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_nqd_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_nqd_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_xi
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_xi

#print axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_beta

#print axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_radiallySymmetric
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_radiallySymmetric

#print axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_exchangeable
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_exchangeable

#print axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_pqd
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.symmetricRightBoundary_pqd

#print axioms Papers.OrendayLaresRockel2026XiBeta.symmetric_right_boundary_attained
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.symmetric_right_boundary_attained

#print axioms Papers.OrendayLaresRockel2026XiBeta.fixed_beta_intermediate_in_class
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.fixed_beta_intermediate_in_class

#print axioms Papers.OrendayLaresRockel2026XiBeta.exact_radiallySymmetric_xi_beta_region
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.exact_radiallySymmetric_xi_beta_region

#print axioms Papers.OrendayLaresRockel2026XiBeta.exact_pqd_xi_beta_region
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.exact_pqd_xi_beta_region

#print axioms Papers.OrendayLaresRockel2026XiBeta.exact_pqd_radiallySymmetric_xi_beta_region
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.exact_pqd_radiallySymmetric_xi_beta_region

#print axioms Papers.OrendayLaresRockel2026XiBeta.exact_nqd_xi_beta_region
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.exact_nqd_xi_beta_region

#print axioms Papers.OrendayLaresRockel2026XiBeta.stochasticUpper_isSI
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.stochasticUpper_isSI

#print axioms Papers.OrendayLaresRockel2026XiBeta.stochasticUpper_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.stochasticUpper_beta

#print axioms Papers.OrendayLaresRockel2026XiBeta.stochasticUpper_xi
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.stochasticUpper_xi

#print axioms Papers.OrendayLaresRockel2026XiBeta.si_inner_region_attained
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.si_inner_region_attained

#print axioms Papers.OrendayLaresRockel2026XiBeta.sd_inner_region_attained
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.sd_inner_region_attained

#print axioms Papers.OrendayLaresRockel2026XiBeta.si_region_outer_bound
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.si_region_outer_bound

#print axioms Papers.OrendayLaresRockel2026XiBeta.sd_region_outer_bound
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.sd_region_outer_bound

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_density
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_density

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_absolutelyContinuous
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_absolutelyContinuous

#print axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_values
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_values

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_transpose_isSI_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_transpose_isSI_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_transpose_isSD_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_transpose_isSD_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_exchangeable_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_exchangeable_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_rho
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_rho

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_tau
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_tau

#print axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_ae_tp2_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_ae_tp2_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_ae_rr2_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_ae_rr2_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_tp2_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_tp2_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_rr2_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.tentDensity_rr2_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_density_version_ae_minors_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_density_version_ae_minors_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_hasMTP2Density_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_hasMTP2Density_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_hasRR2Density_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.leftBoundary_hasRR2Density_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.si_xi_one_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.si_xi_one_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.sd_xi_one_iff
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.sd_xi_one_iff

#print axioms Papers.OrendayLaresRockel2026XiBeta.si_xi_one_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.si_xi_one_beta

#print axioms Papers.OrendayLaresRockel2026XiBeta.sd_xi_one_beta
#assert_standard_axioms Papers.OrendayLaresRockel2026XiBeta.sd_xi_one_beta
