import Papers.Rockel2026XiBlest.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.Rockel2026XiBlest.blest_integrable
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_integrable

#print axioms Papers.Rockel2026XiBlest.blest_integral_formula
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_integral_formula

#print axioms Papers.Rockel2026XiBlest.xi_derivative_formula
#assert_standard_axioms Papers.Rockel2026XiBlest.xi_derivative_formula

#print axioms Papers.Rockel2026XiBlest.blest_mono
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_mono

#print axioms Papers.Rockel2026XiBlest.blest_mix
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_mix

#print axioms Papers.Rockel2026XiBlest.blest_independence
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_independence

#print axioms Papers.Rockel2026XiBlest.xi_zero_slice
#assert_standard_axioms Papers.Rockel2026XiBlest.xi_zero_slice

#print axioms Papers.Rockel2026XiBlest.blest_integral_formula_swapped
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_integral_formula_swapped

#print axioms Papers.Rockel2026XiBlest.blest_comonotonic
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_comonotonic

#print axioms Papers.Rockel2026XiBlest.blest_countermonotonic
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_countermonotonic

#print axioms Papers.Rockel2026XiBlest.blest_mem_Icc
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_mem_Icc

#print axioms Papers.Rockel2026XiBlest.blest_reflect_second
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_reflect_second

#print axioms Papers.Rockel2026XiBlest.xi_blest_reflection
#assert_standard_axioms Papers.Rockel2026XiBlest.xi_blest_reflection

#print axioms Papers.Rockel2026XiBlest.blest_eq_rho_of_radiallySymmetric
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_eq_rho_of_radiallySymmetric

#print axioms Papers.Rockel2026XiBlest.xi_one_slice
#assert_standard_axioms Papers.Rockel2026XiBlest.xi_one_slice

#print axioms Papers.Rockel2026XiBlest.fixed_coefficient_upward
#assert_standard_axioms Papers.Rockel2026XiBlest.fixed_coefficient_upward

#print axioms Papers.Rockel2026XiBlest.attainable_region_convex
#assert_standard_axioms Papers.Rockel2026XiBlest.attainable_region_convex

#print axioms Papers.Rockel2026XiBlest.blest_tendsto_of_cdf
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_tendsto_of_cdf

#print axioms Papers.Rockel2026XiBlest.attainable_region_closed
#assert_standard_axioms Papers.Rockel2026XiBlest.attainable_region_closed

#print axioms Papers.Rockel2026XiBlest.attainable_region_compact
#assert_standard_axioms Papers.Rockel2026XiBlest.attainable_region_compact

#print axioms Papers.Rockel2026XiBlest.blest_extrema_attained
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_extrema_attained

#print axioms Papers.Rockel2026XiBlest.minimal_xi_attained
#assert_standard_axioms Papers.Rockel2026XiBlest.minimal_xi_attained

#print axioms Papers.Rockel2026XiBlest.blest_conditional_formula
#assert_standard_axioms Papers.Rockel2026XiBlest.blest_conditional_formula

#print axioms Papers.Rockel2026XiBlest.extremal_normalization
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_normalization

#print axioms Papers.Rockel2026XiBlest.extremalQ_antitone
#assert_standard_axioms Papers.Rockel2026XiBlest.extremalQ_antitone

#print axioms Papers.Rockel2026XiBlest.extremal_kernel_measurable
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_kernel_measurable

#print axioms Papers.Rockel2026XiBlest.extremal_cdf
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_cdf

#print axioms Papers.Rockel2026XiBlest.extremal_conditionalCDF
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_conditionalCDF

#print axioms Papers.Rockel2026XiBlest.extremal_isSI
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_isSI

#print axioms Papers.Rockel2026XiBlest.clamped_blest_distance_bound
#assert_standard_axioms Papers.Rockel2026XiBlest.clamped_blest_distance_bound

#print axioms Papers.Rockel2026XiBlest.extremal_support
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_support

#print axioms Papers.Rockel2026XiBlest.extremal_support_eq_iff
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_support_eq_iff

#print axioms Papers.Rockel2026XiBlest.extremal_maximal_blest
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_maximal_blest

#print axioms Papers.Rockel2026XiBlest.extremal_maximal_blest_eq_iff
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_maximal_blest_eq_iff

#print axioms Papers.Rockel2026XiBlest.extremal_zero
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_zero

#print axioms Papers.Rockel2026XiBlest.extremal_coefficients_monotone
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_coefficients_monotone

#print axioms Papers.Rockel2026XiBlest.extremal_xi_continuous
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_xi_continuous

#print axioms Papers.Rockel2026XiBlest.extremalSequence_cdf
#assert_standard_axioms Papers.Rockel2026XiBlest.extremalSequence_cdf

#print axioms Papers.Rockel2026XiBlest.extremalSequence_xi
#assert_standard_axioms Papers.Rockel2026XiBlest.extremalSequence_xi

#print axioms Papers.Rockel2026XiBlest.extremalSequence_blest
#assert_standard_axioms Papers.Rockel2026XiBlest.extremalSequence_blest

#print axioms Papers.Rockel2026XiBlest.extremal_parameter_exists
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_parameter_exists

#print axioms Papers.Rockel2026XiBlest.extremal_slice_iff
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_slice_iff

#print axioms Papers.Rockel2026XiBlest.intermediate_slice_characterization
#assert_standard_axioms Papers.Rockel2026XiBlest.intermediate_slice_characterization

#print axioms Papers.Rockel2026XiBlest.extremal_coefficients_polynomial
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_coefficients_polynomial

#print axioms Papers.Rockel2026XiBlest.extremal_one_coefficients
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_one_coefficients

#print axioms Papers.Rockel2026XiBlest.maximal_signed_gap
#assert_standard_axioms Papers.Rockel2026XiBlest.maximal_signed_gap

#print axioms Papers.Rockel2026XiBlest.maximal_signed_gap_eq_iff
#assert_standard_axioms Papers.Rockel2026XiBlest.maximal_signed_gap_eq_iff

#print axioms Papers.Rockel2026XiBlest.maximal_absolute_gap
#assert_standard_axioms Papers.Rockel2026XiBlest.maximal_absolute_gap

#print axioms Papers.Rockel2026XiBlest.maximal_absolute_gap_eq_iff
#assert_standard_axioms Papers.Rockel2026XiBlest.maximal_absolute_gap_eq_iff

#print axioms Papers.Rockel2026XiBlest.extremal_coefficients_strictMono
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_coefficients_strictMono

#print axioms Papers.Rockel2026XiBlest.extremal_finite_xi
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_finite_xi

#print axioms Papers.Rockel2026XiBlest.extremal_positive_xi
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_positive_xi

#print axioms Papers.Rockel2026XiBlest.extremal_parameter_unique
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_parameter_unique

#print axioms Papers.Rockel2026XiBlest.extremal_coefficients_hyperbolic
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_coefficients_hyperbolic

#print axioms Papers.Rockel2026XiBlest.extremal_coefficients
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_coefficients

#print axioms Papers.Rockel2026XiBlest.exact_region
#assert_standard_axioms Papers.Rockel2026XiBlest.exact_region

#print axioms Papers.Rockel2026XiBlest.upper_boundary_unique
#assert_standard_axioms Papers.Rockel2026XiBlest.upper_boundary_unique

#print axioms Papers.Rockel2026XiBlest.lower_boundary_unique
#assert_standard_axioms Papers.Rockel2026XiBlest.lower_boundary_unique

#print axioms Papers.Rockel2026XiBlest.formula_zero
#assert_standard_axioms Papers.Rockel2026XiBlest.formula_zero

#print axioms Papers.Rockel2026XiBlest.formula_zero_limits
#assert_standard_axioms Papers.Rockel2026XiBlest.formula_zero_limits

#print axioms Papers.Rockel2026XiBlest.formula_infinity_limits
#assert_standard_axioms Papers.Rockel2026XiBlest.formula_infinity_limits

#print axioms Papers.Rockel2026XiBlest.formula_hasDerivAt
#assert_standard_axioms Papers.Rockel2026XiBlest.formula_hasDerivAt

#print axioms Papers.Rockel2026XiBlest.formula_derivative_identity
#assert_standard_axioms Papers.Rockel2026XiBlest.formula_derivative_identity

#print axioms Papers.Rockel2026XiBlest.normalizationMean_properties
#assert_standard_axioms Papers.Rockel2026XiBlest.normalizationMean_properties

#print axioms Papers.Rockel2026XiBlest.extremalQ_continuous
#assert_standard_axioms Papers.Rockel2026XiBlest.extremalQ_continuous

#print axioms Papers.Rockel2026XiBlest.extremal_kernel_continuous
#assert_standard_axioms Papers.Rockel2026XiBlest.extremal_kernel_continuous

#print axioms Papers.Rockel2026XiBlest.xi_mixture_continuous
#assert_standard_axioms Papers.Rockel2026XiBlest.xi_mixture_continuous

#print axioms Papers.Rockel2026XiBlest.relaxed_distance_bound
#assert_standard_axioms Papers.Rockel2026XiBlest.relaxed_distance_bound

#print axioms Papers.Rockel2026XiBlest.relaxed_solution
#assert_standard_axioms Papers.Rockel2026XiBlest.relaxed_solution

#print axioms Papers.Rockel2026XiBlest.section_formulas
#assert_standard_axioms Papers.Rockel2026XiBlest.section_formulas

#print axioms Papers.Rockel2026XiBlest.normalizationMean_hasDerivAt
#assert_standard_axioms Papers.Rockel2026XiBlest.normalizationMean_hasDerivAt

#print axioms Papers.Rockel2026XiBlest.normalization_substitution
#assert_standard_axioms Papers.Rockel2026XiBlest.normalization_substitution

#print axioms Papers.Rockel2026XiBlest.one_dimensional_coefficients
#assert_standard_axioms Papers.Rockel2026XiBlest.one_dimensional_coefficients

#print axioms Papers.Rockel2026XiBlest.substitution_upper
#assert_standard_axioms Papers.Rockel2026XiBlest.substitution_upper

#print axioms Papers.Rockel2026XiBlest.substitution_unclamped
#assert_standard_axioms Papers.Rockel2026XiBlest.substitution_unclamped

#print axioms Papers.Rockel2026XiBlest.substitution_double
#assert_standard_axioms Papers.Rockel2026XiBlest.substitution_double

#print axioms Papers.Rockel2026XiBlest.substitution_lower
#assert_standard_axioms Papers.Rockel2026XiBlest.substitution_lower

#print axioms Papers.Rockel2026XiBlest.lower_square_polynomial
#assert_standard_axioms Papers.Rockel2026XiBlest.lower_square_polynomial

#print axioms Papers.Rockel2026XiBlest.printed_lower_square_polynomial_false
#assert_standard_axioms Papers.Rockel2026XiBlest.printed_lower_square_polynomial_false
