import Papers.Rockel2026XiFootrule.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.Rockel2026XiFootrule.xi_derivative_formula
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_derivative_formula

#print axioms Papers.Rockel2026XiFootrule.cdf_upperBoundary
#assert_standard_axioms Papers.Rockel2026XiFootrule.cdf_upperBoundary

#print axioms Papers.Rockel2026XiFootrule.maximal_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.maximal_footrule

#print axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_le
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_le

#print axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_eq_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_eq_iff

#print axioms Papers.Rockel2026XiFootrule.antiCheckerboard_cdf
#assert_standard_axioms Papers.Rockel2026XiFootrule.antiCheckerboard_cdf

#print axioms Papers.Rockel2026XiFootrule.antiCheckerboard_xi
#assert_standard_axioms Papers.Rockel2026XiFootrule.antiCheckerboard_xi

#print axioms Papers.Rockel2026XiFootrule.antiCheckerboard_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.antiCheckerboard_footrule

#print axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_minimal_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_minimal_footrule

#print axioms Papers.Rockel2026XiFootrule.xi_minimum_at_minimal_footrule_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_minimum_at_minimal_footrule_iff

#print axioms Papers.Rockel2026XiFootrule.exact_bottom_boundary
#assert_standard_axioms Papers.Rockel2026XiFootrule.exact_bottom_boundary

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_cdf
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_cdf

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_isSI

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_coefficients
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_coefficients

#print axioms Papers.Rockel2026XiFootrule.si_xi_le_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_xi_le_footrule

#print axioms Papers.Rockel2026XiFootrule.upperBoundary_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.upperBoundary_isSI

#print axioms Papers.Rockel2026XiFootrule.exact_si_xi_footrule_region
#assert_standard_axioms Papers.Rockel2026XiFootrule.exact_si_xi_footrule_region

#print axioms Papers.Rockel2026XiFootrule.ordinalSum_xi_eq_footrule_of_components
#assert_standard_axioms Papers.Rockel2026XiFootrule.ordinalSum_xi_eq_footrule_of_components

#print axioms Papers.Rockel2026XiFootrule.ordinalSum_xi_eq_footrule_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.ordinalSum_xi_eq_footrule_iff

#print axioms Papers.Rockel2026XiFootrule.FinitePiOrdinal.symmetric_rank_equality
#assert_standard_axioms Papers.Rockel2026XiFootrule.FinitePiOrdinal.symmetric_rank_equality
#print axioms Papers.Rockel2026XiFootrule.ordinalSum_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.ordinalSum_isSI

#print axioms Papers.Rockel2026XiFootrule.FinitePiOrdinal.isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.FinitePiOrdinal.isSI

#print axioms Papers.Rockel2026XiFootrule.FinitePiOrdinal.symmetric_si_rank_equality
#assert_standard_axioms Papers.Rockel2026XiFootrule.FinitePiOrdinal.symmetric_si_rank_equality
#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_exchangeable
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_exchangeable

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_diagonal_fixed
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_diagonal_fixed

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_has_binary_split
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_has_binary_split

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_first_lower_component
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_first_lower_component

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_upper_component_tail
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_upper_component_tail

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_recursive
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_recursive

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_gap_recursive
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_gap_recursive

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_xi_eq_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_xi_eq_footrule

#print axioms Papers.Rockel2026XiFootrule.countablePiM_symmetric_rank_equality
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePiM_symmetric_rank_equality

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_cdf_section_eq_of_component_eq
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_cdf_section_eq_of_component_eq

#print axioms Papers.Rockel2026XiFootrule.countablePiM_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePiM_isSI

#print axioms Papers.Rockel2026XiFootrule.countablePiM_symmetric_si_rank_equality
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePiM_symmetric_si_rank_equality

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_isSI

#print axioms Papers.Rockel2026XiFootrule.ordinalSum_isSI_components
#assert_standard_axioms Papers.Rockel2026XiFootrule.ordinalSum_isSI_components

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_isSI_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_isSI_iff

#print axioms Papers.Rockel2026XiFootrule.countableOrdinal_symmetric_si_rank_equality
#assert_standard_axioms Papers.Rockel2026XiFootrule.countableOrdinal_symmetric_si_rank_equality

#print axioms Papers.Rockel2026XiFootrule.countablePi_exchangeable
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePi_exchangeable

#print axioms Papers.Rockel2026XiFootrule.countablePi_diagonal_fixed
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePi_diagonal_fixed

#print axioms Papers.Rockel2026XiFootrule.countablePi_has_binary_split
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePi_has_binary_split
#print axioms Papers.Rockel2026XiFootrule.countablePi_first_lower_component
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePi_first_lower_component
#print axioms Papers.Rockel2026XiFootrule.countablePi_upper_component_tail
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePi_upper_component_tail

#print axioms Papers.Rockel2026XiFootrule.countablePi_recursive
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePi_recursive

#print axioms Papers.Rockel2026XiFootrule.countablePi_gap_recursive
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePi_gap_recursive

#print axioms Papers.Rockel2026XiFootrule.countablePi_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePi_isSI
#print axioms Papers.Rockel2026XiFootrule.countablePi_xi_eq_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.countablePi_xi_eq_footrule
#print axioms Papers.Rockel2026XiFootrule.si_xi_le_three_quarters_tau
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_xi_le_three_quarters_tau

#print axioms Papers.Rockel2026XiFootrule.si_equality_iff_diagonal_moments
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_equality_iff_diagonal_moments

#print axioms Papers.Rockel2026XiFootrule.si_equality_canonical_parameters
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_equality_canonical_parameters

#print axioms Papers.Rockel2026XiFootrule.si_equality_iff_conditional_threeLevel
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_equality_iff_conditional_threeLevel

#print axioms Papers.Rockel2026XiFootrule.si_equality_iff_derivative_threeLevel
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_equality_iff_derivative_threeLevel

#print axioms Papers.Rockel2026XiFootrule.jensen_profile_formula
#assert_standard_axioms Papers.Rockel2026XiFootrule.jensen_profile_formula

#print axioms Papers.Rockel2026XiFootrule.jensen_profile_feasible
#assert_standard_axioms Papers.Rockel2026XiFootrule.jensen_profile_feasible

#print axioms Papers.Rockel2026XiFootrule.scalar_optimizer_minimum
#assert_standard_axioms Papers.Rockel2026XiFootrule.scalar_optimizer_minimum

#print axioms Papers.Rockel2026XiFootrule.scalar_optimizer_unique
#assert_standard_axioms Papers.Rockel2026XiFootrule.scalar_optimizer_unique

#print axioms Papers.Rockel2026XiFootrule.conditional_jensen_bound
#assert_standard_axioms Papers.Rockel2026XiFootrule.conditional_jensen_bound

#print axioms Papers.Rockel2026XiFootrule.conditional_jensen_equality
#assert_standard_axioms Papers.Rockel2026XiFootrule.conditional_jensen_equality

#print axioms Papers.Rockel2026XiFootrule.relaxed_values_integral_form
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_values_integral_form

#print axioms Papers.Rockel2026XiFootrule.weighted_lower_bound
#assert_standard_axioms Papers.Rockel2026XiFootrule.weighted_lower_bound

#print axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_relaxed_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_relaxed_footrule

#print axioms Papers.Rockel2026XiFootrule.relaxed_family_not_copula
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_family_not_copula

#print axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_closed
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_closed

#print axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_continuous
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_continuous

#print axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_strict_monotonicity
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_strict_monotonicity

#print axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_endpoints
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_endpoints

#print axioms Papers.Rockel2026XiFootrule.footrule_inverse_unique
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_inverse_unique

#print axioms Papers.Rockel2026XiFootrule.footrule_cubic_equivalence
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_cubic_equivalence

#print axioms Papers.Rockel2026XiFootrule.footrule_cubic_unique_admissible
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_cubic_unique_admissible

#print axioms Papers.Rockel2026XiFootrule.footrule_cubic_not_unique_real
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_cubic_not_unique_real

#print axioms Papers.Rockel2026XiFootrule.weighted_lower_bound_closed
#assert_standard_axioms Papers.Rockel2026XiFootrule.weighted_lower_bound_closed

#print axioms Papers.Rockel2026XiFootrule.negative_footrule_lower_bound
#assert_standard_axioms Papers.Rockel2026XiFootrule.negative_footrule_lower_bound

#print axioms Papers.Rockel2026XiFootrule.rightBoundary_coefficients
#assert_standard_axioms Papers.Rockel2026XiFootrule.rightBoundary_coefficients

#print axioms Papers.Rockel2026XiFootrule.xi_one_slice
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_one_slice

#print axioms Papers.Rockel2026XiFootrule.fixed_footrule_intermediate
#assert_standard_axioms Papers.Rockel2026XiFootrule.fixed_footrule_intermediate

#print axioms Papers.Rockel2026XiFootrule.fixed_footrule_upward
#assert_standard_axioms Papers.Rockel2026XiFootrule.fixed_footrule_upward

#print axioms Papers.Rockel2026XiFootrule.attainable_region_convex
#assert_standard_axioms Papers.Rockel2026XiFootrule.attainable_region_convex

#print axioms Papers.Rockel2026XiFootrule.exact_nonnegative_footrule_region
#assert_standard_axioms Papers.Rockel2026XiFootrule.exact_nonnegative_footrule_region

#print axioms Papers.Rockel2026XiFootrule.asymmetricEquality_cdf
#assert_standard_axioms Papers.Rockel2026XiFootrule.asymmetricEquality_cdf

#print axioms Papers.Rockel2026XiFootrule.asymmetricEquality_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.asymmetricEquality_isSI

#print axioms Papers.Rockel2026XiFootrule.asymmetricEquality_conditionalCDF
#assert_standard_axioms Papers.Rockel2026XiFootrule.asymmetricEquality_conditionalCDF

#print axioms Papers.Rockel2026XiFootrule.asymmetricEquality_derivative
#assert_standard_axioms Papers.Rockel2026XiFootrule.asymmetricEquality_derivative

#print axioms Papers.Rockel2026XiFootrule.asymmetricEquality_xi_eq_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.asymmetricEquality_xi_eq_footrule

#print axioms Papers.Rockel2026XiFootrule.asymmetricEquality_coefficients
#assert_standard_axioms Papers.Rockel2026XiFootrule.asymmetricEquality_coefficients

#print axioms Papers.Rockel2026XiFootrule.asymmetricEquality_asymmetry_witness
#assert_standard_axioms Papers.Rockel2026XiFootrule.asymmetricEquality_asymmetry_witness

#print axioms Papers.Rockel2026XiFootrule.asymmetricEquality_not_exchangeable
#assert_standard_axioms Papers.Rockel2026XiFootrule.asymmetricEquality_not_exchangeable

#print axioms Papers.Rockel2026XiFootrule.frechet_coefficients
#assert_standard_axioms Papers.Rockel2026XiFootrule.frechet_coefficients

#print axioms Papers.Rockel2026XiFootrule.frechet_objective_lower
#assert_standard_axioms Papers.Rockel2026XiFootrule.frechet_objective_lower

#print axioms Papers.Rockel2026XiFootrule.frechet_objective_eq_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.frechet_objective_eq_iff

#print axioms Papers.Rockel2026XiFootrule.frechet_minimizer_coefficients
#assert_standard_axioms Papers.Rockel2026XiFootrule.frechet_minimizer_coefficients

#print axioms Papers.Rockel2026XiFootrule.twoParameter_raw_marginals
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_raw_marginals

#print axioms Papers.Rockel2026XiFootrule.twoParameter_marginal_density
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_marginal_density

#print axioms Papers.Rockel2026XiFootrule.twoParameter_density
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_density

#print axioms Papers.Rockel2026XiFootrule.twoParameter_zero_width
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_zero_width

#print axioms Papers.Rockel2026XiFootrule.twoParameter_corner
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_corner

#print axioms Papers.Rockel2026XiFootrule.twoParameter_corner_coefficients
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_corner_coefficients

#print axioms Papers.Rockel2026XiFootrule.twoParameter_path_admissible
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_path_admissible

#print axioms Papers.Rockel2026XiFootrule.twoParameter_path_zero
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_path_zero

#print axioms Papers.Rockel2026XiFootrule.footrule_tendsto_of_cdf
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_tendsto_of_cdf

#print axioms Papers.Rockel2026XiFootrule.attainable_region_closed
#assert_standard_axioms Papers.Rockel2026XiFootrule.attainable_region_closed

#print axioms Papers.Rockel2026XiFootrule.attainable_region_compact
#assert_standard_axioms Papers.Rockel2026XiFootrule.attainable_region_compact

#print axioms Papers.Rockel2026XiFootrule.minimal_footrule_attained
#assert_standard_axioms Papers.Rockel2026XiFootrule.minimal_footrule_attained

#print axioms Papers.Rockel2026XiFootrule.minimal_xi_attained
#assert_standard_axioms Papers.Rockel2026XiFootrule.minimal_xi_attained

#print axioms Papers.Rockel2026XiFootrule.printed_ltd_matrix
#assert_standard_axioms Papers.Rockel2026XiFootrule.printed_ltd_matrix

#print axioms Papers.Rockel2026XiFootrule.printed_ltd_coefficients
#assert_standard_axioms Papers.Rockel2026XiFootrule.printed_ltd_coefficients

#print axioms Papers.Rockel2026XiFootrule.printed_ltd_claim_false
#assert_standard_axioms Papers.Rockel2026XiFootrule.printed_ltd_claim_false

#print axioms Papers.Rockel2026XiFootrule.corrected_ltd_matrix
#assert_standard_axioms Papers.Rockel2026XiFootrule.corrected_ltd_matrix

#print axioms Papers.Rockel2026XiFootrule.corrected_ltd_counterexample
#assert_standard_axioms Papers.Rockel2026XiFootrule.corrected_ltd_counterexample

#print axioms Papers.Rockel2026XiFootrule.corrected_ltd_not_si
#assert_standard_axioms Papers.Rockel2026XiFootrule.corrected_ltd_not_si

#print axioms Papers.Rockel2026XiFootrule.upperBoundary_isLowerSemilinear
#assert_standard_axioms Papers.Rockel2026XiFootrule.upperBoundary_isLowerSemilinear

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_isLowerSemilinear
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_isLowerSemilinear

#print axioms Papers.Rockel2026XiFootrule.lowerSemilinear_xi_le_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.lowerSemilinear_xi_le_footrule

#print axioms Papers.Rockel2026XiFootrule.exact_lowerSemilinear_xi_footrule_region
#assert_standard_axioms Papers.Rockel2026XiFootrule.exact_lowerSemilinear_xi_footrule_region

#print axioms Papers.Rockel2026XiFootrule.lowerSemilinear_region_eq_si
#assert_standard_axioms Papers.Rockel2026XiFootrule.lowerSemilinear_region_eq_si

#print axioms Papers.Rockel2026XiFootrule.relaxed_mirrored_bound
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_mirrored_bound

#print axioms Papers.Rockel2026XiFootrule.negative_footrule_strict
#assert_standard_axioms Papers.Rockel2026XiFootrule.negative_footrule_strict

#print axioms Papers.Rockel2026XiFootrule.abs_footrule_le_sqrt_xi
#assert_standard_axioms Papers.Rockel2026XiFootrule.abs_footrule_le_sqrt_xi

#print axioms Papers.Rockel2026XiFootrule.abs_footrule_eq_sqrt_xi_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.abs_footrule_eq_sqrt_xi_iff

#print axioms Papers.Rockel2026XiFootrule.footrule_pair_attained_as_rho
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_pair_attained_as_rho

#print axioms Papers.Rockel2026XiFootrule.footrule_region_ssubset_rho_region
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_region_ssubset_rho_region

#print axioms Papers.Rockel2026XiFootrule.twoParameter_parameters_continuous
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_parameters_continuous

#print axioms Papers.Rockel2026XiFootrule.twoParameter_parameters_limit
#assert_standard_axioms Papers.Rockel2026XiFootrule.twoParameter_parameters_limit
