import Papers.Rockel2026XiFootrule.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.Rockel2026XiFootrule.xi_derivative_formula
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_derivative_formula

#print axioms Papers.Rockel2026XiFootrule.cdf_upperBoundary
#assert_standard_axioms Papers.Rockel2026XiFootrule.cdf_upperBoundary

#print axioms Papers.Rockel2026XiFootrule.maximal_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.maximal_footrule

#print axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_le
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_le

#print axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_eq_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_eq_iff

#print axioms Papers.Rockel2026XiFootrule.antiCheckerboard_cdf
#assert_standard_axioms Papers.Rockel2026XiFootrule.antiCheckerboard_cdf

#print axioms Papers.Rockel2026XiFootrule.antiCheckerboard_xi
#assert_standard_axioms Papers.Rockel2026XiFootrule.antiCheckerboard_xi

#print axioms Papers.Rockel2026XiFootrule.antiCheckerboard_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.antiCheckerboard_footrule

#print axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_minimal_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_minimal_footrule

#print axioms Papers.Rockel2026XiFootrule.xi_minimum_at_minimal_footrule_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_minimum_at_minimal_footrule_iff

#print axioms Papers.Rockel2026XiFootrule.exact_bottom_boundary
#assert_standard_axioms Papers.Rockel2026XiFootrule.exact_bottom_boundary

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_cdf
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_cdf

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_isSI

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_coefficients
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_coefficients

#print axioms Papers.Rockel2026XiFootrule.si_xi_le_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_xi_le_footrule

#print axioms Papers.Rockel2026XiFootrule.upperBoundary_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.upperBoundary_isSI

#print axioms Papers.Rockel2026XiFootrule.exact_si_xi_footrule_region
#assert_standard_axioms Papers.Rockel2026XiFootrule.exact_si_xi_footrule_region

#print axioms Papers.Rockel2026XiFootrule.si_xi_le_three_quarters_tau
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_xi_le_three_quarters_tau

#print axioms Papers.Rockel2026XiFootrule.si_equality_iff_diagonal_moments
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_equality_iff_diagonal_moments

#print axioms Papers.Rockel2026XiFootrule.si_equality_canonical_parameters
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_equality_canonical_parameters

#print axioms Papers.Rockel2026XiFootrule.si_equality_iff_conditional_threeLevel
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_equality_iff_conditional_threeLevel

#print axioms Papers.Rockel2026XiFootrule.si_equality_iff_derivative_threeLevel
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_equality_iff_derivative_threeLevel

#print axioms Papers.Rockel2026XiFootrule.jensen_profile_formula
#assert_standard_axioms Papers.Rockel2026XiFootrule.jensen_profile_formula

#print axioms Papers.Rockel2026XiFootrule.jensen_profile_feasible
#assert_standard_axioms Papers.Rockel2026XiFootrule.jensen_profile_feasible

#print axioms Papers.Rockel2026XiFootrule.scalar_optimizer_minimum
#assert_standard_axioms Papers.Rockel2026XiFootrule.scalar_optimizer_minimum

#print axioms Papers.Rockel2026XiFootrule.scalar_optimizer_unique
#assert_standard_axioms Papers.Rockel2026XiFootrule.scalar_optimizer_unique

#print axioms Papers.Rockel2026XiFootrule.conditional_jensen_bound
#assert_standard_axioms Papers.Rockel2026XiFootrule.conditional_jensen_bound

#print axioms Papers.Rockel2026XiFootrule.conditional_jensen_equality
#assert_standard_axioms Papers.Rockel2026XiFootrule.conditional_jensen_equality

#print axioms Papers.Rockel2026XiFootrule.relaxed_values_integral_form
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_values_integral_form

#print axioms Papers.Rockel2026XiFootrule.weighted_lower_bound
#assert_standard_axioms Papers.Rockel2026XiFootrule.weighted_lower_bound

#print axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_relaxed_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_relaxed_footrule

#print axioms Papers.Rockel2026XiFootrule.relaxed_family_not_copula
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_family_not_copula

#print axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_closed
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_closed

#print axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_continuous
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_continuous

#print axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_strict_monotonicity
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_strict_monotonicity

#print axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_endpoints
#assert_standard_axioms Papers.Rockel2026XiFootrule.relaxed_coefficients_endpoints

#print axioms Papers.Rockel2026XiFootrule.footrule_inverse_unique
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_inverse_unique

#print axioms Papers.Rockel2026XiFootrule.footrule_cubic_equivalence
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_cubic_equivalence

#print axioms Papers.Rockel2026XiFootrule.footrule_cubic_unique_admissible
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_cubic_unique_admissible

#print axioms Papers.Rockel2026XiFootrule.footrule_cubic_not_unique_real
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_cubic_not_unique_real

#print axioms Papers.Rockel2026XiFootrule.weighted_lower_bound_closed
#assert_standard_axioms Papers.Rockel2026XiFootrule.weighted_lower_bound_closed

#print axioms Papers.Rockel2026XiFootrule.negative_footrule_lower_bound
#assert_standard_axioms Papers.Rockel2026XiFootrule.negative_footrule_lower_bound
