import Papers.Rockel2026XiFootrule.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.Rockel2026XiFootrule.xi_derivative_formula
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_derivative_formula

#print axioms Papers.Rockel2026XiFootrule.cdf_upperBoundary
#assert_standard_axioms Papers.Rockel2026XiFootrule.cdf_upperBoundary

#print axioms Papers.Rockel2026XiFootrule.maximal_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.maximal_footrule

#print axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_le
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_le

#print axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_eq_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.footrule_sub_xi_eq_iff

#print axioms Papers.Rockel2026XiFootrule.antiCheckerboard_cdf
#assert_standard_axioms Papers.Rockel2026XiFootrule.antiCheckerboard_cdf

#print axioms Papers.Rockel2026XiFootrule.antiCheckerboard_xi
#assert_standard_axioms Papers.Rockel2026XiFootrule.antiCheckerboard_xi

#print axioms Papers.Rockel2026XiFootrule.antiCheckerboard_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.antiCheckerboard_footrule

#print axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_minimal_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_lower_bound_at_minimal_footrule

#print axioms Papers.Rockel2026XiFootrule.xi_minimum_at_minimal_footrule_iff
#assert_standard_axioms Papers.Rockel2026XiFootrule.xi_minimum_at_minimal_footrule_iff

#print axioms Papers.Rockel2026XiFootrule.exact_bottom_boundary
#assert_standard_axioms Papers.Rockel2026XiFootrule.exact_bottom_boundary

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_cdf
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_cdf

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_isSI

#print axioms Papers.Rockel2026XiFootrule.diagonalBoundary_coefficients
#assert_standard_axioms Papers.Rockel2026XiFootrule.diagonalBoundary_coefficients

#print axioms Papers.Rockel2026XiFootrule.si_xi_le_footrule
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_xi_le_footrule

#print axioms Papers.Rockel2026XiFootrule.upperBoundary_isSI
#assert_standard_axioms Papers.Rockel2026XiFootrule.upperBoundary_isSI

#print axioms Papers.Rockel2026XiFootrule.exact_si_xi_footrule_region
#assert_standard_axioms Papers.Rockel2026XiFootrule.exact_si_xi_footrule_region

#print axioms Papers.Rockel2026XiFootrule.si_xi_le_three_quarters_tau
#assert_standard_axioms Papers.Rockel2026XiFootrule.si_xi_le_three_quarters_tau
