import Papers.AnsariRockel2026XiRho.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockel2026XiRho.xi_derivative_formula
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_derivative_formula

#print axioms Papers.AnsariRockel2026XiRho.xi_zero_slice
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_zero_slice

#print axioms Papers.AnsariRockel2026XiRho.rho_extreme_implies_xi_one
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_extreme_implies_xi_one

#print axioms Papers.AnsariRockel2026XiRho.fgm_stochastically_monotone
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fgm_stochastically_monotone

#print axioms Papers.AnsariRockel2026XiRho.fgm_xi_le_abs_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fgm_xi_le_abs_rho

#print axioms Papers.AnsariRockel2026XiRho.fgm_xi_eq_abs_rho_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fgm_xi_eq_abs_rho_iff
