import Papers.AnsariRockel2026XiRho.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockel2026XiRho.xi_derivative_formula
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_derivative_formula

#print axioms Papers.AnsariRockel2026XiRho.xi_zero_slice
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_zero_slice

#print axioms Papers.AnsariRockel2026XiRho.rho_extreme_implies_xi_one
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_extreme_implies_xi_one

#print axioms Papers.AnsariRockel2026XiRho.fgm_stochastically_monotone
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fgm_stochastically_monotone

#print axioms Papers.AnsariRockel2026XiRho.fgm_xi_le_abs_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fgm_xi_le_abs_rho

#print axioms Papers.AnsariRockel2026XiRho.fgm_xi_eq_abs_rho_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fgm_xi_eq_abs_rho_iff

#print axioms Papers.AnsariRockel2026XiRho.xi_one_slice
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_one_slice

#print axioms Papers.AnsariRockel2026XiRho.symmetric_xi_one_attained
#assert_standard_axioms Papers.AnsariRockel2026XiRho.symmetric_xi_one_attained

#print axioms Papers.AnsariRockel2026XiRho.rho_conditionalCDF_formula
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_conditionalCDF_formula

#print axioms Papers.AnsariRockel2026XiRho.rho_derivative_formula
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_derivative_formula

#print axioms Papers.AnsariRockel2026XiRho.si_xi_le_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.si_xi_le_rho

#print axioms Papers.AnsariRockel2026XiRho.sd_xi_le_neg_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sd_xi_le_neg_rho

#print axioms Papers.AnsariRockel2026XiRho.stochastic_xi_le_abs_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.stochastic_xi_le_abs_rho

#print axioms Papers.AnsariRockel2026XiRho.not_stochastically_monotone_of_abs_rho_lt_xi
#assert_standard_axioms Papers.AnsariRockel2026XiRho.not_stochastically_monotone_of_abs_rho_lt_xi

#print axioms Papers.AnsariRockel2026XiRho.lemma8_bound
#assert_standard_axioms Papers.AnsariRockel2026XiRho.lemma8_bound

#print axioms Papers.AnsariRockel2026XiRho.lemma8_equality
#assert_standard_axioms Papers.AnsariRockel2026XiRho.lemma8_equality

#print axioms Papers.AnsariRockel2026XiRho.si_xi_eq_rho_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.si_xi_eq_rho_iff

#print axioms Papers.AnsariRockel2026XiRho.sd_xi_eq_neg_rho_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sd_xi_eq_neg_rho_iff

#print axioms Papers.AnsariRockel2026XiRho.stochastic_xi_eq_abs_rho_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.stochastic_xi_eq_abs_rho_iff

#print axioms Papers.AnsariRockel2026XiRho.stochastic_xi_lt_abs_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.stochastic_xi_lt_abs_rho

#print axioms Papers.AnsariRockel2026XiRho.fixed_coefficient_upward
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fixed_coefficient_upward

#print axioms Papers.AnsariRockel2026XiRho.attainable_region_convex
#assert_standard_axioms Papers.AnsariRockel2026XiRho.attainable_region_convex

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_cdf
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_cdf

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_conditionalCDF

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_derivative
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_derivative

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_isSI
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_isSI

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_xi
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_xi

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_rho

#print axioms Papers.AnsariRockel2026XiRho.rho_sub_xi_le
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_sub_xi_le

#print axioms Papers.AnsariRockel2026XiRho.rho_sub_xi_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_sub_xi_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.sharp_gap_attained
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sharp_gap_attained

#print axioms Papers.AnsariRockel2026XiRho.abs_rho_sub_xi_le
#assert_standard_axioms Papers.AnsariRockel2026XiRho.abs_rho_sub_xi_le

#print axioms Papers.AnsariRockel2026XiRho.abs_rho_sub_xi_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.abs_rho_sub_xi_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.xi_three_tenths_slice
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_three_tenths_slice

#print axioms Papers.AnsariRockel2026XiRho.xi_three_tenths_rho_max_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_three_tenths_rho_max_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_conditionalCDF

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_isSI
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_isSI

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_support
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_support

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_support_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_support_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_maximal_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_maximal_rho

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_maximal_rho_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_maximal_rho_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_zero
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_zero

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_one
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_one

#print axioms Papers.AnsariRockel2026XiRho.sourceBandIntercept_mean
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBandIntercept_mean

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_eq_normalizedBand
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_eq_normalizedBand

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_cdf
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_cdf

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_conditionalCDF

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_derivative
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_derivative

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_xi
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_xi

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_rho

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_coefficients
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_coefficients

#print axioms Papers.AnsariRockel2026XiRho.smallXiParameter_inverse
#assert_standard_axioms Papers.AnsariRockel2026XiRho.smallXiParameter_inverse

#print axioms Papers.AnsariRockel2026XiRho.largeXiParameter_inverse
#assert_standard_axioms Papers.AnsariRockel2026XiRho.largeXiParameter_inverse

#print axioms Papers.AnsariRockel2026XiRho.boundaryParameter_inverse
#assert_standard_axioms Papers.AnsariRockel2026XiRho.boundaryParameter_inverse

#print axioms Papers.AnsariRockel2026XiRho.boundaryCopula_coefficients
#assert_standard_axioms Papers.AnsariRockel2026XiRho.boundaryCopula_coefficients

#print axioms Papers.AnsariRockel2026XiRho.sharp_absolute_rho_bound
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sharp_absolute_rho_bound

#print axioms Papers.AnsariRockel2026XiRho.exact_region
#assert_standard_axioms Papers.AnsariRockel2026XiRho.exact_region

#print axioms Papers.AnsariRockel2026XiRho.upper_boundary_unique
#assert_standard_axioms Papers.AnsariRockel2026XiRho.upper_boundary_unique

#print axioms Papers.AnsariRockel2026XiRho.lower_boundary_unique
#assert_standard_axioms Papers.AnsariRockel2026XiRho.lower_boundary_unique

#print axioms Papers.AnsariRockel2026XiRho.explicit_band_support
#assert_standard_axioms Papers.AnsariRockel2026XiRho.explicit_band_support

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_radially_symmetric
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_radially_symmetric

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_radially_symmetric
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_radially_symmetric

#print axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_cdf
#assert_standard_axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_cdf

#print axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_coefficients
#assert_standard_axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_coefficients

#print axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_eq_response_reflection
#assert_standard_axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_eq_response_reflection

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_parameter_order
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_parameter_order

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_parameter_order
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_parameter_order

#print axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_parameter_order
#assert_standard_axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_parameter_order

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_independence_error
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_independence_error

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_comonotonic_error
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_comonotonic_error

#print axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_independence_error
#assert_standard_axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_independence_error

#print axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_countermonotonic_error
#assert_standard_axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_countermonotonic_error

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_tendstoUniformly_zero
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_tendstoUniformly_zero

#print axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_tendstoUniformly_zero
#assert_standard_axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_tendstoUniformly_zero

#print axioms Papers.AnsariRockel2026XiRho.sourceBand_tendstoUniformly_atTop
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sourceBand_tendstoUniformly_atTop

#print axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_tendstoUniformly_atTop
#assert_standard_axioms Papers.AnsariRockel2026XiRho.negativeSourceBand_tendstoUniformly_atTop

#print axioms Papers.AnsariRockel2026XiRho.plodShuffle_cdf
#assert_standard_axioms Papers.AnsariRockel2026XiRho.plodShuffle_cdf

#print axioms Papers.AnsariRockel2026XiRho.plodShuffle_isPQD
#assert_standard_axioms Papers.AnsariRockel2026XiRho.plodShuffle_isPQD

#print axioms Papers.AnsariRockel2026XiRho.plodShuffle_xi
#assert_standard_axioms Papers.AnsariRockel2026XiRho.plodShuffle_xi

#print axioms Papers.AnsariRockel2026XiRho.plodShuffle_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.plodShuffle_rho

#print axioms Papers.AnsariRockel2026XiRho.plod_counterexample
#assert_standard_axioms Papers.AnsariRockel2026XiRho.plod_counterexample
