import Papers.AnsariRockel2026XiRho.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockel2026XiRho.xi_derivative_formula
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_derivative_formula

#print axioms Papers.AnsariRockel2026XiRho.xi_zero_slice
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_zero_slice

#print axioms Papers.AnsariRockel2026XiRho.rho_extreme_implies_xi_one
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_extreme_implies_xi_one

#print axioms Papers.AnsariRockel2026XiRho.fgm_stochastically_monotone
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fgm_stochastically_monotone

#print axioms Papers.AnsariRockel2026XiRho.fgm_xi_le_abs_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fgm_xi_le_abs_rho

#print axioms Papers.AnsariRockel2026XiRho.fgm_xi_eq_abs_rho_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fgm_xi_eq_abs_rho_iff

#print axioms Papers.AnsariRockel2026XiRho.xi_one_slice
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_one_slice

#print axioms Papers.AnsariRockel2026XiRho.symmetric_xi_one_attained
#assert_standard_axioms Papers.AnsariRockel2026XiRho.symmetric_xi_one_attained

#print axioms Papers.AnsariRockel2026XiRho.rho_conditionalCDF_formula
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_conditionalCDF_formula

#print axioms Papers.AnsariRockel2026XiRho.rho_derivative_formula
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_derivative_formula

#print axioms Papers.AnsariRockel2026XiRho.si_xi_le_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.si_xi_le_rho

#print axioms Papers.AnsariRockel2026XiRho.sd_xi_le_neg_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sd_xi_le_neg_rho

#print axioms Papers.AnsariRockel2026XiRho.stochastic_xi_le_abs_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.stochastic_xi_le_abs_rho

#print axioms Papers.AnsariRockel2026XiRho.not_stochastically_monotone_of_abs_rho_lt_xi
#assert_standard_axioms Papers.AnsariRockel2026XiRho.not_stochastically_monotone_of_abs_rho_lt_xi

#print axioms Papers.AnsariRockel2026XiRho.lemma8_bound
#assert_standard_axioms Papers.AnsariRockel2026XiRho.lemma8_bound

#print axioms Papers.AnsariRockel2026XiRho.lemma8_equality
#assert_standard_axioms Papers.AnsariRockel2026XiRho.lemma8_equality

#print axioms Papers.AnsariRockel2026XiRho.si_xi_eq_rho_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.si_xi_eq_rho_iff

#print axioms Papers.AnsariRockel2026XiRho.sd_xi_eq_neg_rho_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sd_xi_eq_neg_rho_iff

#print axioms Papers.AnsariRockel2026XiRho.stochastic_xi_eq_abs_rho_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.stochastic_xi_eq_abs_rho_iff

#print axioms Papers.AnsariRockel2026XiRho.stochastic_xi_lt_abs_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.stochastic_xi_lt_abs_rho

#print axioms Papers.AnsariRockel2026XiRho.fixed_coefficient_upward
#assert_standard_axioms Papers.AnsariRockel2026XiRho.fixed_coefficient_upward

#print axioms Papers.AnsariRockel2026XiRho.attainable_region_convex
#assert_standard_axioms Papers.AnsariRockel2026XiRho.attainable_region_convex

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_cdf
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_cdf

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_conditionalCDF

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_derivative
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_derivative

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_isSI
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_isSI

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_xi
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_xi

#print axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.unitDiagonalBand_rho

#print axioms Papers.AnsariRockel2026XiRho.rho_sub_xi_le
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_sub_xi_le

#print axioms Papers.AnsariRockel2026XiRho.rho_sub_xi_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.rho_sub_xi_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.sharp_gap_attained
#assert_standard_axioms Papers.AnsariRockel2026XiRho.sharp_gap_attained

#print axioms Papers.AnsariRockel2026XiRho.abs_rho_sub_xi_le
#assert_standard_axioms Papers.AnsariRockel2026XiRho.abs_rho_sub_xi_le

#print axioms Papers.AnsariRockel2026XiRho.abs_rho_sub_xi_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.abs_rho_sub_xi_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.xi_three_tenths_slice
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_three_tenths_slice

#print axioms Papers.AnsariRockel2026XiRho.xi_three_tenths_rho_max_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.xi_three_tenths_rho_max_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_conditionalCDF

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_isSI
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_isSI

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_support
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_support

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_support_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_support_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_maximal_rho
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_maximal_rho

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_maximal_rho_eq_iff
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_maximal_rho_eq_iff

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_zero
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_zero

#print axioms Papers.AnsariRockel2026XiRho.normalizedBand_one
#assert_standard_axioms Papers.AnsariRockel2026XiRho.normalizedBand_one
