import Papers.Rockel2026ExactBlest.Main
import Verification.AxiomAudit

#print axioms Papers.Rockel2026ExactBlest.LambdaInv_bijOn
#assert_standard_axioms Papers.Rockel2026ExactBlest.LambdaInv_bijOn
#print axioms Papers.Rockel2026ExactBlest.LambdaInv_strictMonoOn
#assert_standard_axioms Papers.Rockel2026ExactBlest.LambdaInv_strictMonoOn
#print axioms Papers.Rockel2026ExactBlest.Lambda_bijOn
#assert_standard_axioms Papers.Rockel2026ExactBlest.Lambda_bijOn
#print axioms Papers.Rockel2026ExactBlest.Lambda_curve
#assert_standard_axioms Papers.Rockel2026ExactBlest.Lambda_curve
#print axioms Papers.Rockel2026ExactBlest.Lambda_junction
#assert_standard_axioms Papers.Rockel2026ExactBlest.Lambda_junction
#print axioms Papers.Rockel2026ExactBlest.Lambda_paperNB
#assert_standard_axioms Papers.Rockel2026ExactBlest.Lambda_paperNB
#print axioms Papers.Rockel2026ExactBlest.Lambda_strictMonoOn
#assert_standard_axioms Papers.Rockel2026ExactBlest.Lambda_strictMonoOn
#print axioms Papers.Rockel2026ExactBlest.ae_coord_ne
#assert_standard_axioms Papers.Rockel2026ExactBlest.ae_coord_ne
#print axioms Papers.Rockel2026ExactBlest.copula_eq_of_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.copula_eq_of_graph
#print axioms Papers.Rockel2026ExactBlest.copula_eq_of_reverse_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.copula_eq_of_reverse_graph
#print axioms Papers.Rockel2026ExactBlest.cutB_paper
#assert_standard_axioms Papers.Rockel2026ExactBlest.cutB_paper
#print axioms Papers.Rockel2026ExactBlest.deriv_paperEtaB_pos
#assert_standard_axioms Papers.Rockel2026ExactBlest.deriv_paperEtaB_pos
#print axioms Papers.Rockel2026ExactBlest.dual_certificate
#assert_standard_axioms Papers.Rockel2026ExactBlest.dual_certificate
#print axioms Papers.Rockel2026ExactBlest.dual_certificate_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.dual_certificate_graph
#print axioms Papers.Rockel2026ExactBlest.dual_certificate_reverse_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.dual_certificate_reverse_graph
#print axioms Papers.Rockel2026ExactBlest.etaGap_continuousAt_join
#assert_standard_axioms Papers.Rockel2026ExactBlest.etaGap_continuousAt_join
#print axioms Papers.Rockel2026ExactBlest.etaGap_continuousOn
#assert_standard_axioms Papers.Rockel2026ExactBlest.etaGap_continuousOn
#print axioms Papers.Rockel2026ExactBlest.etaGap_join
#assert_standard_axioms Papers.Rockel2026ExactBlest.etaGap_join
#print axioms Papers.Rockel2026ExactBlest.etaGap_mem
#assert_standard_axioms Papers.Rockel2026ExactBlest.etaGap_mem
#print axioms Papers.Rockel2026ExactBlest.etaGap_paperEtaB
#assert_standard_axioms Papers.Rockel2026ExactBlest.etaGap_paperEtaB
#print axioms Papers.Rockel2026ExactBlest.etaGap_randomized_bounds
#assert_standard_axioms Papers.Rockel2026ExactBlest.etaGap_randomized_bounds
#print axioms Papers.Rockel2026ExactBlest.eta_bottom_fibre
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_bottom_fibre
#print axioms Papers.Rockel2026ExactBlest.eta_bottom_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_bottom_unique
#print axioms Papers.Rockel2026ExactBlest.eta_fibre_displayed
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_fibre_displayed
#print axioms Papers.Rockel2026ExactBlest.eta_fibre_max_asymmetry
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_fibre_max_asymmetry
#print axioms Papers.Rockel2026ExactBlest.eta_lower_eq_transpose_upper
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_lower_eq_transpose_upper
#print axioms Papers.Rockel2026ExactBlest.eta_lower_exists_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_lower_exists_unique
#print axioms Papers.Rockel2026ExactBlest.eta_mix
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_mix
#print axioms Papers.Rockel2026ExactBlest.eta_moment
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_moment
#print axioms Papers.Rockel2026ExactBlest.eta_nu_fibre_reflect
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_nu_fibre_reflect
#print axioms Papers.Rockel2026ExactBlest.eta_nu_region
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_nu_region
#print axioms Papers.Rockel2026ExactBlest.eta_nu_region_linear_image
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_nu_region_linear_image
#print axioms Papers.Rockel2026ExactBlest.eta_nu_region_not_symmetric
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_nu_region_not_symmetric
#print axioms Papers.Rockel2026ExactBlest.eta_paperA
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_paperA
#print axioms Papers.Rockel2026ExactBlest.eta_paperA_strictMono
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_paperA_strictMono
#print axioms Papers.Rockel2026ExactBlest.eta_paperB
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_paperB
#print axioms Papers.Rockel2026ExactBlest.eta_reflect_second
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_reflect_second
#print axioms Papers.Rockel2026ExactBlest.eta_survival
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_survival
#print axioms Papers.Rockel2026ExactBlest.eta_upper_exists_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.eta_upper_exists_unique
#print axioms Papers.Rockel2026ExactBlest.familyB_disintegration
#assert_standard_axioms Papers.Rockel2026ExactBlest.familyB_disintegration
#print axioms Papers.Rockel2026ExactBlest.familyB_joint_law
#assert_standard_axioms Papers.Rockel2026ExactBlest.familyB_joint_law
#print axioms Papers.Rockel2026ExactBlest.familyB_not_first_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.familyB_not_first_graph
#print axioms Papers.Rockel2026ExactBlest.gap_band_iff
#assert_standard_axioms Papers.Rockel2026ExactBlest.gap_band_iff
#print axioms Papers.Rockel2026ExactBlest.graphGap_deriv_bounds
#assert_standard_axioms Papers.Rockel2026ExactBlest.graphGap_deriv_bounds
#print axioms Papers.Rockel2026ExactBlest.graph_fibre
#assert_standard_axioms Papers.Rockel2026ExactBlest.graph_fibre
#print axioms Papers.Rockel2026ExactBlest.graph_support
#assert_standard_axioms Papers.Rockel2026ExactBlest.graph_support
#print axioms Papers.Rockel2026ExactBlest.graph_support_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.graph_support_graph
#print axioms Papers.Rockel2026ExactBlest.graph_upper_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.graph_upper_unique
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_etaGap_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_etaGap_graph
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_etaGap_paper
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_etaGap_paper
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_etaGap_param
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_etaGap_param
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_graphGap
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_graphGap
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperEtaB
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperEtaB
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperPhiA
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperPhiA
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperPhiB
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperPhiB
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperPsiA
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperPsiA
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperPsiB
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperPsiB
#print axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperUps
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivAt_paperUps
#print axioms Papers.Rockel2026ExactBlest.hasDerivWithinAt_etaGap_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.hasDerivWithinAt_etaGap_graph
#print axioms Papers.Rockel2026ExactBlest.kA_paper
#assert_standard_axioms Papers.Rockel2026ExactBlest.kA_paper
#print axioms Papers.Rockel2026ExactBlest.kB_paper
#assert_standard_axioms Papers.Rockel2026ExactBlest.kB_paper
#print axioms Papers.Rockel2026ExactBlest.lowerCurve_strictMonoOn
#assert_standard_axioms Papers.Rockel2026ExactBlest.lowerCurve_strictMonoOn
#print axioms Papers.Rockel2026ExactBlest.lower_boundary_curve
#assert_standard_axioms Papers.Rockel2026ExactBlest.lower_boundary_curve
#print axioms Papers.Rockel2026ExactBlest.no_opposite_extremes
#assert_standard_axioms Papers.Rockel2026ExactBlest.no_opposite_extremes
#print axioms Papers.Rockel2026ExactBlest.nu_eta_bound
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_eta_bound
#print axioms Papers.Rockel2026ExactBlest.nu_moment
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_moment
#print axioms Papers.Rockel2026ExactBlest.nu_normalization
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_normalization
#print axioms Papers.Rockel2026ExactBlest.nu_paperA
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_paperA
#print axioms Papers.Rockel2026ExactBlest.nu_paperB
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_paperB
#print axioms Papers.Rockel2026ExactBlest.nu_reflect_first
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_reflect_first
#print axioms Papers.Rockel2026ExactBlest.nu_rho_bound
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_rho_bound
#print axioms Papers.Rockel2026ExactBlest.nu_rho_moment
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_rho_moment
#print axioms Papers.Rockel2026ExactBlest.nu_survival
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_survival
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_bound
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_bound
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_closed_bound
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_closed_bound
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_closed_bound_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_closed_bound_unique
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_extremizer_neg_one
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_extremizer_neg_one
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_fibre_eq
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_fibre_eq
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_half_bound
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_half_bound
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_isGreatest
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_isGreatest
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_isLeast
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_isLeast
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_max_exists_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_max_exists_unique
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_min_exists_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_min_exists_unique
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_moment
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_moment
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_neg_one_values
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_neg_one_values
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_paperA
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_paperA
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_paperB
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_paperB
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_region
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_region
#print axioms Papers.Rockel2026ExactBlest.nu_transpose_region_gap
#assert_standard_axioms Papers.Rockel2026ExactBlest.nu_transpose_region_gap
#print axioms Papers.Rockel2026ExactBlest.paperA_eta_range
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperA_eta_range
#print axioms Papers.Rockel2026ExactBlest.paperA_gap
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperA_gap
#print axioms Papers.Rockel2026ExactBlest.paperA_graph_law
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperA_graph_law
#print axioms Papers.Rockel2026ExactBlest.paperA_not_extremal
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperA_not_extremal
#print axioms Papers.Rockel2026ExactBlest.paperA_one
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperA_one
#print axioms Papers.Rockel2026ExactBlest.paperA_threeQuarter_values
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperA_threeQuarter_values
#print axioms Papers.Rockel2026ExactBlest.paperA_zero
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperA_zero
#print axioms Papers.Rockel2026ExactBlest.paperB_conditional_formula
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperB_conditional_formula
#print axioms Papers.Rockel2026ExactBlest.paperB_gap
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperB_gap
#print axioms Papers.Rockel2026ExactBlest.paperB_graph_law
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperB_graph_law
#print axioms Papers.Rockel2026ExactBlest.paperB_half
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperB_half
#print axioms Papers.Rockel2026ExactBlest.paperB_zero
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperB_zero
#print axioms Papers.Rockel2026ExactBlest.paperD_graph_law
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperD_graph_law
#print axioms Papers.Rockel2026ExactBlest.paperD_half
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperD_half
#print axioms Papers.Rockel2026ExactBlest.paperD_on_boundary
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperD_on_boundary
#print axioms Papers.Rockel2026ExactBlest.paperD_one
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperD_one
#print axioms Papers.Rockel2026ExactBlest.paperD_parameter_exists_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperD_parameter_exists_unique
#print axioms Papers.Rockel2026ExactBlest.paperD_parameter_range
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperD_parameter_range
#print axioms Papers.Rockel2026ExactBlest.paperD_strictMono
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperD_strictMono
#print axioms Papers.Rockel2026ExactBlest.paperD_values
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperD_values
#print axioms Papers.Rockel2026ExactBlest.paperD_zero
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperD_zero
#print axioms Papers.Rockel2026ExactBlest.paperEtaB_endpoints
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperEtaB_endpoints
#print axioms Papers.Rockel2026ExactBlest.paperEtaB_range
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperEtaB_range
#print axioms Papers.Rockel2026ExactBlest.paperEtaB_strictMonoOn
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperEtaB_strictMonoOn
#print axioms Papers.Rockel2026ExactBlest.paperNB_bijOn
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperNB_bijOn
#print axioms Papers.Rockel2026ExactBlest.paperPotentialsA_normalized
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperPotentialsA_normalized
#print axioms Papers.Rockel2026ExactBlest.paperPotentialsB_normalized
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperPotentialsB_normalized
#print axioms Papers.Rockel2026ExactBlest.paperR_formula
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperR_formula
#print axioms Papers.Rockel2026ExactBlest.paperT_formula
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperT_formula
#print axioms Papers.Rockel2026ExactBlest.paperUps_deriv_pos
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperUps_deriv_pos
#print axioms Papers.Rockel2026ExactBlest.paperZeta_formula
#assert_standard_axioms Papers.Rockel2026ExactBlest.paperZeta_formula
#print axioms Papers.Rockel2026ExactBlest.paper_Lambda_junction
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_Lambda_junction
#print axioms Papers.Rockel2026ExactBlest.paper_asymmetry_eq_iff
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_asymmetry_eq_iff
#print axioms Papers.Rockel2026ExactBlest.paper_contactA
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_contactA
#print axioms Papers.Rockel2026ExactBlest.paper_contactB
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_contactB
#print axioms Papers.Rockel2026ExactBlest.paper_dualA
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_dualA
#print axioms Papers.Rockel2026ExactBlest.paper_dualB
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_dualB
#print axioms Papers.Rockel2026ExactBlest.paper_eta_graph_extremizers
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_eta_graph_extremizers
#print axioms Papers.Rockel2026ExactBlest.paper_eta_random_extremizers
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_eta_random_extremizers
#print axioms Papers.Rockel2026ExactBlest.paper_figure_panel_values
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_figure_panel_values
#print axioms Papers.Rockel2026ExactBlest.paper_nu_rho_max_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_nu_rho_max_unique
#print axioms Papers.Rockel2026ExactBlest.paper_nu_rho_min_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_nu_rho_min_unique
#print axioms Papers.Rockel2026ExactBlest.paper_nu_transpose_extremizer_cases
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_nu_transpose_extremizer_cases
#print axioms Papers.Rockel2026ExactBlest.paper_nu_transpose_max_A
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_nu_transpose_max_A
#print axioms Papers.Rockel2026ExactBlest.paper_nu_transpose_max_B
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_nu_transpose_max_B
#print axioms Papers.Rockel2026ExactBlest.paper_rho_eta_extremizers
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_rho_eta_extremizers
#print axioms Papers.Rockel2026ExactBlest.paper_rho_lower_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_rho_lower_unique
#print axioms Papers.Rockel2026ExactBlest.paper_rho_upper_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_rho_upper_unique
#print axioms Papers.Rockel2026ExactBlest.paper_transposition_eq_iff
#assert_standard_axioms Papers.Rockel2026ExactBlest.paper_transposition_eq_iff
#print axioms Papers.Rockel2026ExactBlest.param_slope_bounds
#assert_standard_axioms Papers.Rockel2026ExactBlest.param_slope_bounds
#print axioms Papers.Rockel2026ExactBlest.quadraticRank_half
#assert_standard_axioms Papers.Rockel2026ExactBlest.quadraticRank_half
#print axioms Papers.Rockel2026ExactBlest.quadraticRank_uniform
#assert_standard_axioms Papers.Rockel2026ExactBlest.quadraticRank_uniform
#print axioms Papers.Rockel2026ExactBlest.randomGap_endpoints
#assert_standard_axioms Papers.Rockel2026ExactBlest.randomGap_endpoints
#print axioms Papers.Rockel2026ExactBlest.randomGap_strictAnti
#assert_standard_axioms Papers.Rockel2026ExactBlest.randomGap_strictAnti
#print axioms Papers.Rockel2026ExactBlest.random_branches_same_derivative
#assert_standard_axioms Papers.Rockel2026ExactBlest.random_branches_same_derivative
#print axioms Papers.Rockel2026ExactBlest.randomized_fibre
#assert_standard_axioms Papers.Rockel2026ExactBlest.randomized_fibre
#print axioms Papers.Rockel2026ExactBlest.randomized_optimizer_not_first_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.randomized_optimizer_not_first_graph
#print axioms Papers.Rockel2026ExactBlest.randomized_support
#assert_standard_axioms Papers.Rockel2026ExactBlest.randomized_support
#print axioms Papers.Rockel2026ExactBlest.randomized_support_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.randomized_support_graph
#print axioms Papers.Rockel2026ExactBlest.randomized_upper_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.randomized_upper_unique
#print axioms Papers.Rockel2026ExactBlest.rearrangement
#assert_standard_axioms Papers.Rockel2026ExactBlest.rearrangement
#print axioms Papers.Rockel2026ExactBlest.reflection_byproduct
#assert_standard_axioms Papers.Rockel2026ExactBlest.reflection_byproduct
#print axioms Papers.Rockel2026ExactBlest.rhoBoundary_reflect
#assert_standard_axioms Papers.Rockel2026ExactBlest.rhoBoundary_reflect
#print axioms Papers.Rockel2026ExactBlest.rho_eta_bound
#assert_standard_axioms Papers.Rockel2026ExactBlest.rho_eta_bound
#print axioms Papers.Rockel2026ExactBlest.rho_lower_eq_survival_upper
#assert_standard_axioms Papers.Rockel2026ExactBlest.rho_lower_eq_survival_upper
#print axioms Papers.Rockel2026ExactBlest.rho_lower_exists_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.rho_lower_exists_unique
#print axioms Papers.Rockel2026ExactBlest.rho_midpoint_original_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.rho_midpoint_original_graph
#print axioms Papers.Rockel2026ExactBlest.rho_midpoint_reflected_graph
#assert_standard_axioms Papers.Rockel2026ExactBlest.rho_midpoint_reflected_graph
#print axioms Papers.Rockel2026ExactBlest.rho_nu_fibre_reflect
#assert_standard_axioms Papers.Rockel2026ExactBlest.rho_nu_fibre_reflect
#print axioms Papers.Rockel2026ExactBlest.rho_nu_region
#assert_standard_axioms Papers.Rockel2026ExactBlest.rho_nu_region
#print axioms Papers.Rockel2026ExactBlest.rho_nu_region_neg
#assert_standard_axioms Papers.Rockel2026ExactBlest.rho_nu_region_neg
#print axioms Papers.Rockel2026ExactBlest.rho_upper_exists_unique
#assert_standard_axioms Papers.Rockel2026ExactBlest.rho_upper_exists_unique
#print axioms Papers.Rockel2026ExactBlest.support_moment_survival
#assert_standard_axioms Papers.Rockel2026ExactBlest.support_moment_survival
#print axioms Papers.Rockel2026ExactBlest.threshold_rearrangement
#assert_standard_axioms Papers.Rockel2026ExactBlest.threshold_rearrangement
#print axioms Papers.Rockel2026ExactBlest.upperCurve_strictMonoOn
#assert_standard_axioms Papers.Rockel2026ExactBlest.upperCurve_strictMonoOn
#print axioms Papers.Rockel2026ExactBlest.upper_boundary_curve
#assert_standard_axioms Papers.Rockel2026ExactBlest.upper_boundary_curve
#print axioms Papers.Rockel2026ExactBlest.weighted_tail_layercake
#assert_standard_axioms Papers.Rockel2026ExactBlest.weighted_tail_layercake
