import Papers.AnsariRockelSteinmassl2026RhoGamma.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.moment_representation
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.moment_representation

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.reflection_pair
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.reflection_pair

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.fixed_gamma_intermediate
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.fixed_gamma_intermediate

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_convex
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_convex

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_centrally_symmetric
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_centrally_symmetric

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.rankMagnitude_uniform
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.rankMagnitude_uniform

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.magnitude_marginal
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.magnitude_marginal

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_product_identity
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_product_identity

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_min_magnitude_identity
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_min_magnitude_identity

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_magnitude_rho
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_magnitude_rho

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_magnitude_gamma
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_magnitude_gamma

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_functional
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_functional

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_functional_le
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_functional_le

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_weak_duality
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_weak_duality

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_value
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_value

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_optimal
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_optimal

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_zero
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_zero

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_integral
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_integral

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_feasible
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_feasible

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_lipschitz
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_lipschitz

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_deriv_bound
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_deriv_bound

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_cost
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_cost

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_optimal
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_optimal

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_contact
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_contact

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signCopula_joint_law
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signCopula_joint_law

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signCopula_magnitude_law
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signCopula_magnitude_law

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signCopula_rho
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signCopula_rho

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signCopula_gamma
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signCopula_gamma

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signOptimizer_magnitude
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signOptimizer_magnitude

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signOptimizer_value
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.signOptimizer_value

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_bound_attained
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_bound_attained

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_bound_iff_transport_bound
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_bound_iff_transport_bound

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_optimizer_lifts
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_optimizer_lifts

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transportValue_attained
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transportValue_attained

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_maximum
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_maximum

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_support
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_support

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.boundary_coefficients
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.boundary_coefficients

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_parameter
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_parameter

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sharp_upper_bound
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sharp_upper_bound

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sharp_lower_bound
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sharp_lower_bound

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upper_boundary_attained
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upper_boundary_attained

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.lower_boundary_attained
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.lower_boundary_attained

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.exact_region
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.exact_region

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.boundary_value_unique
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.boundary_value_unique

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.glued_dual_feasible
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.glued_dual_feasible

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sharp_supporting_bound
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sharp_supporting_bound

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_compact
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_compact

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_endpoints
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_endpoints

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_concave
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_concave

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_strictMono
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_strictMono

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_continuous
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_continuous

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.discrepancy_support_slope
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.discrepancy_support_slope

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.discrepancy_coefficients
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.discrepancy_coefficients

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.discrepancy_value
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.discrepancy_value

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.rho_sub_gamma_le
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.rho_sub_gamma_le

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.abs_rho_sub_gamma_le
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.abs_rho_sub_gamma_le

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.maximal_discrepancy_attained
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.maximal_discrepancy_attained

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_zero
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_zero

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_neg_gammaThreshold
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upperRho_neg_gammaThreshold

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.zero_gamma_slice
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.zero_gamma_slice

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.zero_rho_slice
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.zero_rho_slice

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.same_sign_of_abs_rho_gt
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.same_sign_of_abs_rho_gt

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.same_sign_of_abs_gamma_gt
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.same_sign_of_abs_gamma_gt

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_arc_coefficients
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_arc_coefficients

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_arc_closed
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_arc_closed

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_arc_coverage
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_arc_coverage

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_upper_boundary
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_upper_boundary

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_not_optimal
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_not_optimal

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_optimal_iff
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_optimal_iff

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_slope_covered
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_slope_covered

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_primal_dual_attained
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_primal_dual_attained

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_strong_duality
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_strong_duality

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transportValue_eq_dual_infimum
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transportValue_eq_dual_infimum

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.source_splitting_formulas
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.source_splitting_formulas

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.source_parameter_inequalities
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.source_parameter_inequalities

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.source_alpha_matching
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.source_alpha_matching

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.right_source_data
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.right_source_data

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.left_source_data
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.left_source_data

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaCertificate_s
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaCertificate_s

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaCertificate_data
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaCertificate_data

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sourceTheta_thetaCertificate
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sourceTheta_thetaCertificate

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_splitting
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_splitting

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_boundary_coefficients
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_boundary_coefficients

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_boundary_maximizes
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_boundary_maximizes

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_boundary_value
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_boundary_value

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_parameter_inequalities
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_parameter_inequalities

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_shuffle_support
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_shuffle_support

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_shuffle_graph
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_shuffle_graph

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_shuffle_law
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_shuffle_law

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_shuffle_measurePreserving
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_shuffle_measurePreserving

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_endpoint_constants
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_endpoint_constants

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_d_coverage
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.elementary_d_coverage

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.five_piece_shuffle_realizes_boundary
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.five_piece_shuffle_realizes_boundary

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upper_boundary_cubic_remainder
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upper_boundary_cubic_remainder

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upper_boundary_asymptotic
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.upper_boundary_asymptotic

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.continuous_thetaInput
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.continuous_thetaInput

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.continuous_theta_coordinates
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.continuous_theta_coordinates

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.continuous_theta_coordinates_nonnegative
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.continuous_theta_coordinates_nonnegative

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaAlpha_integer
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaAlpha_integer

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_integer_coordinates
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_integer_coordinates

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaG_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaG_tendsto_atTop

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaG_tendsto_zero
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaG_tendsto_zero

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_coordinates_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_coordinates_tendsto_atTop

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_coordinates_tendsto_zero
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_coordinates_tendsto_zero

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_coordinates_zero
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_coordinates_zero

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_gamma_coverage
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_gamma_coverage

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_gamma_full_range
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_gamma_full_range

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaCertificate_width
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.thetaCertificate_width

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_auxiliary_potential
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_auxiliary_potential

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_potential_derivative
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_potential_derivative

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_discriminant_inequalities
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_discriminant_inequalities

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_distance_distribution
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_distance_distribution

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_atom_mass_bounds
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_atom_mass_bounds

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_delta_bound
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_delta_bound

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_midpoint_atom_zero
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_midpoint_atom_zero

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.glued_copula_probability_law
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.glued_copula_probability_law

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_transport_value
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_transport_value

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_supporting_inequality
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.theta_supporting_inequality
