import Papers.AnsariRockelSteinmassl2026RhoGamma.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.moment_representation
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.moment_representation

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.reflection_pair
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.reflection_pair

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.fixed_gamma_intermediate
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.fixed_gamma_intermediate

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_convex
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_convex

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_centrally_symmetric
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_centrally_symmetric
