import Papers.AnsariRockelSteinmassl2026RhoGamma.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.moment_representation
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.moment_representation

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.reflection_pair
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.reflection_pair

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.fixed_gamma_intermediate
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.fixed_gamma_intermediate

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_convex
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_convex

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_centrally_symmetric
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.region_centrally_symmetric

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.rankMagnitude_uniform
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.rankMagnitude_uniform

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.magnitude_marginal
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.magnitude_marginal

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_product_identity
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_product_identity

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_min_magnitude_identity
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_min_magnitude_identity

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_magnitude_rho
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_magnitude_rho

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_magnitude_gamma
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.sign_magnitude_gamma

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_functional
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_functional

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_functional_le
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.supporting_functional_le

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_weak_duality
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_weak_duality

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_value
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_value

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_optimal
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.transport_contact_optimal

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_zero
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_zero

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_integral
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_integral

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_feasible
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_feasible

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_lipschitz
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_lipschitz

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_deriv_bound
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_deriv_bound

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_cost
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_cost

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_optimal
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShift_optimal

#print axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_contact
#assert_standard_axioms Papers.AnsariRockelSteinmassl2026RhoGamma.halfShiftPotential_contact
