import Papers.AnsariRockelSteinmassl2026RhoGamma.ThetaEndpoints
import Papers.AnsariRockelSteinmassl2026RhoGamma.ThetaJunctions
import Papers.AnsariRockelSteinmassl2026RhoGamma.ThetaDistanceLaw
import Papers.AnsariRockelSteinmassl2026RhoGamma.GluedLaw
import Papers.AnsariRockelSteinmassl2026RhoGamma.ThetaSupporting
import Papers.AnsariRockelSteinmassl2026RhoGamma.StrongDuality
import Papers.AnsariRockelSteinmassl2026RhoGamma.ThetaBoundary
import Papers.AnsariRockelSteinmassl2026RhoGamma.ElementaryEndpoints
import Papers.AnsariRockelSteinmassl2026RhoGamma.BoundaryAsymptotic
import Papers.AnsariRockelSteinmassl2026RhoGamma.ElementaryArc
import Papers.AnsariRockelSteinmassl2026RhoGamma.SignThresholds
import Papers.AnsariRockelSteinmassl2026RhoGamma.SharpDiscrepancy
import Papers.AnsariRockelSteinmassl2026RhoGamma.BoundaryGeometry
import Papers.AnsariRockelSteinmassl2026RhoGamma.ExactRegion
import Papers.AnsariRockelSteinmassl2026RhoGamma.SignAttainment
import Papers.AnsariRockelSteinmassl2026RhoGamma.SignMagnitude
import Papers.AnsariRockelSteinmassl2026RhoGamma.Transport
import Papers.AnsariRockelSteinmassl2026RhoGamma.HalfShift
import Papers.AnsariRockelSteinmassl2026RhoGamma.Moments

/-! # AnsariRockelSteinmassl2026RhoGamma: public results

See `COVERAGE.md` for the exact verified subset and remaining obligations.
-/
