import Papers.AnsariRockel2024.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockel2024.clayton_positive_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_cdf
#print axioms Papers.AnsariRockel2024.clayton_cdf_positive_eq_analytic
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_positive_eq_analytic

#print axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_first
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_first

#print axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_second
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_second

#print axioms Papers.AnsariRockel2024.clayton_mixed_derivative_eq_densityFormula
#assert_standard_axioms Papers.AnsariRockel2024.clayton_mixed_derivative_eq_densityFormula

#print axioms Papers.AnsariRockel2024.clayton_density_formula_integral_second
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_integral_second

#print axioms Papers.AnsariRockel2024.clayton_cdf_formula_integral_first
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_formula_integral_first

#print axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle

#print axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_densityFormula_positive_rectangle_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_densityFormula_positive_rectangle_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_withDensity_positive_rectangle_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_positive_rectangle_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_withDensity_axis_zero
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_axis_zero

#print axioms Papers.AnsariRockel2024.clayton_withDensity_positive_lowerOrthant_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_positive_lowerOrthant_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_withDensity_lowerOrthant_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_lowerOrthant_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_toMeasure_eq_withDensity_positive
#assert_standard_axioms Papers.AnsariRockel2024.clayton_toMeasure_eq_withDensity_positive

#print axioms Papers.AnsariRockel2024.clayton_positive_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_density_tp2

#print axioms Papers.AnsariRockel2024.clayton_positive_absolutelyContinuous
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_absolutelyContinuous

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_bounds
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_bounds

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_tendsto_one
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_tendsto_one

#print axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_cdf_bounds
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_cdf_bounds

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_rectangle_tendsto_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_rectangle_tendsto_cdf

#print axioms Papers.AnsariRockel2024.clayton_negative_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_cdf
#print axioms Papers.AnsariRockel2024.clayton_positive_zero_axes
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_zero_axes
#print axioms Papers.AnsariRockel2024.clayton_negative_zero_axes
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_zero_axes
#print axioms Papers.AnsariRockel2024.clayton_one_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_one_cdf

#print axioms Papers.AnsariRockel2024.clayton_zero_ci_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_zero_ci_cd
#print axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_one_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one_cd

#print axioms Papers.AnsariRockel2024.clayton_negative_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_cd

#print axioms Papers.AnsariRockel2024.clayton_negative_nqd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_nqd

#print axioms Papers.AnsariRockel2024.clayton_positive_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_not_cd
#print axioms Papers.AnsariRockel2024.clayton_negative_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_not_ci

#print axioms Papers.AnsariRockel2024.clayton_positive_ci
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_ci

#print axioms Papers.AnsariRockel2024.clayton_positive_pqd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_pqd

#print axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_one
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one
#print axioms Papers.AnsariRockel2024.clayton_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.clayton_tendsto_zero
#print axioms Papers.AnsariRockel2024.clayton_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.clayton_tendsto_atTop

#print axioms Papers.AnsariRockel2024.classical_representation
#assert_standard_axioms Papers.AnsariRockel2024.classical_representation

#print axioms Papers.AnsariRockel2024.fgm_cdf
#assert_standard_axioms Papers.AnsariRockel2024.fgm_cdf

#print axioms Papers.AnsariRockel2024.xi_derivative_formula
#assert_standard_axioms Papers.AnsariRockel2024.xi_derivative_formula

#print axioms Papers.AnsariRockel2024.fgm_rho
#assert_standard_axioms Papers.AnsariRockel2024.fgm_rho

#print axioms Papers.AnsariRockel2024.fgm_tau
#assert_standard_axioms Papers.AnsariRockel2024.fgm_tau

#print axioms Papers.AnsariRockel2024.fgm_xi
#assert_standard_axioms Papers.AnsariRockel2024.fgm_xi

#print axioms Papers.AnsariRockel2024.frechet_rho
#assert_standard_axioms Papers.AnsariRockel2024.frechet_rho

#print axioms Papers.AnsariRockel2024.frechet_tau
#assert_standard_axioms Papers.AnsariRockel2024.frechet_tau

#print axioms Papers.AnsariRockel2024.frechet_xi
#assert_standard_axioms Papers.AnsariRockel2024.frechet_xi

#print axioms Papers.AnsariRockel2024.mardia_rho
#assert_standard_axioms Papers.AnsariRockel2024.mardia_rho

#print axioms Papers.AnsariRockel2024.mardia_tau
#assert_standard_axioms Papers.AnsariRockel2024.mardia_tau

#print axioms Papers.AnsariRockel2024.mardia_xi
#assert_standard_axioms Papers.AnsariRockel2024.mardia_xi

#print axioms Papers.AnsariRockel2024.fgm_ci
#assert_standard_axioms Papers.AnsariRockel2024.fgm_ci

#print axioms Papers.AnsariRockel2024.fgm_cd
#assert_standard_axioms Papers.AnsariRockel2024.fgm_cd

#print axioms Papers.AnsariRockel2024.fgm_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.fgm_lowerOrthant

#print axioms Papers.AnsariRockel2024.fgm_tails
#assert_standard_axioms Papers.AnsariRockel2024.fgm_tails

#print axioms Papers.AnsariRockel2024.frechet_tails
#assert_standard_axioms Papers.AnsariRockel2024.frechet_tails

#print axioms Papers.AnsariRockel2024.mardia_tails
#assert_standard_axioms Papers.AnsariRockel2024.mardia_tails

#print axioms Papers.AnsariRockel2024.fgm_density
#assert_standard_axioms Papers.AnsariRockel2024.fgm_density

#print axioms Papers.AnsariRockel2024.fgm_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.fgm_density_tp2_iff

#print axioms Papers.AnsariRockel2024.fgm_has_tp2_density
#assert_standard_axioms Papers.AnsariRockel2024.fgm_has_tp2_density

#print axioms Papers.AnsariRockel2024.nelsen7_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_cdf

#print axioms Papers.AnsariRockel2024.nelsen7_endpoints
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_endpoints

#print axioms Papers.AnsariRockel2024.nelsen7_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_cd

#print axioms Papers.AnsariRockel2024.nelsen7_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.nelsen7_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tails

#print axioms Papers.AnsariRockel2024.gumbel_tails
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_tails

#print axioms Papers.AnsariRockel2024.marshallOlkin_tails
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_tails

#print axioms Papers.AnsariRockel2024.cuadrasAuge_tails
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_tails

#print axioms Papers.AnsariRockel2024.tawn_tails
#assert_standard_axioms Papers.AnsariRockel2024.tawn_tails

#print axioms Papers.AnsariRockel2024.fgm_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.fgm_schur_iff

#print axioms Papers.AnsariRockel2024.frechet_parameter_order
#assert_standard_axioms Papers.AnsariRockel2024.frechet_parameter_order

#print axioms Papers.AnsariRockel2024.frechet_order_counterexample
#assert_standard_axioms Papers.AnsariRockel2024.frechet_order_counterexample

#print axioms Papers.AnsariRockel2024.frechet_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_ci_iff

#print axioms Papers.AnsariRockel2024.frechet_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_cd_iff

#print axioms Papers.AnsariRockel2024.frechet_absolutelyContinuous_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_absolutelyContinuous_iff

#print axioms Papers.AnsariRockel2024.frechet_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_density_tp2_iff

#print axioms Papers.AnsariRockel2024.mardia_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_ci_iff

#print axioms Papers.AnsariRockel2024.mardia_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_cd_iff

#print axioms Papers.AnsariRockel2024.mardia_absolutelyContinuous_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_absolutelyContinuous_iff

#print axioms Papers.AnsariRockel2024.mardia_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_density_tp2_iff

#print axioms Papers.AnsariRockel2024.mardia_not_lowerOrthant_ordered
#assert_standard_axioms Papers.AnsariRockel2024.mardia_not_lowerOrthant_ordered

#print axioms Papers.AnsariRockel2024.nelsen7_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_conditionalCDF

#print axioms Papers.AnsariRockel2024.nelsen7_derivative
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_derivative

#print axioms Papers.AnsariRockel2024.nelsen7_xi
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_xi

#print axioms Papers.AnsariRockel2024.nelsen7_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen7_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_schur_iff

#print axioms Papers.AnsariRockel2024.survival_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.survival_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.survival_cis_iff
#assert_standard_axioms Papers.AnsariRockel2024.survival_cis_iff

#print axioms Papers.AnsariRockel2024.survival_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.survival_schur_iff

#print axioms Papers.AnsariRockel2024.concordance_coefficients_mono
#assert_standard_axioms Papers.AnsariRockel2024.concordance_coefficients_mono

#print axioms Papers.AnsariRockel2024.schur_xi_mono
#assert_standard_axioms Papers.AnsariRockel2024.schur_xi_mono

#print axioms Papers.AnsariRockel2024.lower_tail_mono
#assert_standard_axioms Papers.AnsariRockel2024.lower_tail_mono

#print axioms Papers.AnsariRockel2024.upper_tail_mono
#assert_standard_axioms Papers.AnsariRockel2024.upper_tail_mono

#print axioms Papers.AnsariRockel2024.schur_below_cis
#assert_standard_axioms Papers.AnsariRockel2024.schur_below_cis

#print axioms Papers.AnsariRockel2024.schur_below_cds
#assert_standard_axioms Papers.AnsariRockel2024.schur_below_cds

#print axioms Papers.AnsariRockel2024.cis_schur_iff_orthant
#assert_standard_axioms Papers.AnsariRockel2024.cis_schur_iff_orthant
#print axioms Papers.AnsariRockel2024.cds_schur_iff_reverse_orthant
#assert_standard_axioms Papers.AnsariRockel2024.cds_schur_iff_reverse_orthant

#print axioms Papers.AnsariRockel2024.extremeValue_schur_first_iff_pickands_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_first_iff_pickands_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_schur_second_iff_pickands_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_second_iff_pickands_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_tail_mono
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_tail_mono
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_concordance_mono
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_concordance_mono
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_xi_mono_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_xi_mono_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_schur_iff_pickands_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_iff_pickands_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_order
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_order
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_representation
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_representation
#print axioms Papers.AnsariRockel2024.marshallOlkin_rho
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_rho

#print axioms Papers.AnsariRockel2024.marshallOlkin_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_conditionalCDF

#print axioms Papers.AnsariRockel2024.marshallOlkin_xi
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_xi

#print axioms Papers.AnsariRockel2024.marshallOlkin_tau
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_tau

#print axioms Papers.AnsariRockel2024.marshallOlkin_cdf
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_cdf
#print axioms Papers.AnsariRockel2024.marshallOlkin_ci
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_ci
#print axioms Papers.AnsariRockel2024.marshallOlkin_orthant_mono
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_orthant_mono
#print axioms Papers.AnsariRockel2024.marshallOlkin_schur_mono
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_schur_mono
#print axioms Papers.AnsariRockel2024.cuadrasAuge_ci
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_ci
#print axioms Papers.AnsariRockel2024.cuadrasAuge_orthant_mono
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_orthant_mono
#print axioms Papers.AnsariRockel2024.cuadrasAuge_schur_mono
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_schur_mono

#print axioms Papers.AnsariRockel2024.cuadrasAuge_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_conditionalCDF
#print axioms Papers.AnsariRockel2024.cuadrasAuge_rho
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_rho
#print axioms Papers.AnsariRockel2024.cuadrasAuge_xi
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_xi

#print axioms Papers.AnsariRockel2024.cuadrasAuge_tau
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_tau

#print axioms Papers.AnsariRockel2024.marshallOlkin_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_density_tp2
#print axioms Papers.AnsariRockel2024.marshallOlkin_absolutelyContinuous
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_absolutelyContinuous
#print axioms Papers.AnsariRockel2024.marshallOlkin_independence_axes
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_independence_axes
#print axioms Papers.AnsariRockel2024.cuadrasAuge_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_density_tp2
#print axioms Papers.AnsariRockel2024.cuadrasAuge_absolutelyContinuous
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_absolutelyContinuous

#print axioms Papers.AnsariRockel2024.clayton_positive_cdf_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_cdf_tp2
#print axioms Papers.AnsariRockel2024.clayton_zero_cdf_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_zero_cdf_tp2
#print axioms Papers.AnsariRockel2024.clayton_negative_not_cdf_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_not_cdf_tp2

#print axioms Papers.AnsariRockel2024.clayton_negative_one_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one_not_density_tp2

#print axioms Papers.AnsariRockel2024.hasMTP2Density_isPQD
#assert_standard_axioms Papers.AnsariRockel2024.hasMTP2Density_isPQD

#print axioms Papers.AnsariRockel2024.clayton_negative_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_not_density_tp2

#print axioms Papers.AnsariRockel2024.isCD_eq_independence_of_hasMTP2Density
#assert_standard_axioms Papers.AnsariRockel2024.isCD_eq_independence_of_hasMTP2Density

#print axioms Papers.AnsariRockel2024.isCD_eq_independence_of_isTP2CDF
#assert_standard_axioms Papers.AnsariRockel2024.isCD_eq_independence_of_isTP2CDF

#print axioms Papers.AnsariRockel2024.nelsen7_cdf_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_cdf_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen7_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_density_tp2_iff

#print axioms Papers.AnsariRockel2024.fgm_hasMTP2Density_iff
#assert_standard_axioms Papers.AnsariRockel2024.fgm_hasMTP2Density_iff

#print axioms Papers.AnsariRockel2024.nelsen7_integral_cdf_first
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_integral_cdf_first
#print axioms Papers.AnsariRockel2024.nelsen7_rho_integral
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_rho_integral
#print axioms Papers.AnsariRockel2024.nelsen7_rho_interior
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_rho_interior
#print axioms Papers.AnsariRockel2024.nelsen7_rho
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_rho
#print axioms Papers.AnsariRockel2024.nelsen7_tau_rho
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tau_rho
#print axioms Papers.AnsariRockel2024.nelsen7_tau_interior
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tau_interior
#print axioms Papers.AnsariRockel2024.nelsen7_tau
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tau
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_expanded
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_expanded
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_formula
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_formula
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_zero
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_identity_false_half
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_identity_false_half
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_identity_false
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_identity_false

#print axioms Papers.AnsariRockel2024.gumbel_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_cdf_full

#print axioms Papers.AnsariRockel2024.gumbel_one
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_one

#print axioms Papers.AnsariRockel2024.gumbel_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_tendsto_atTop

#print axioms Papers.AnsariRockel2024.gumbel_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_lowerOrthant
#print axioms Papers.AnsariRockel2024.tawn_cdf_positive
#assert_standard_axioms Papers.AnsariRockel2024.tawn_cdf_positive
#print axioms Papers.AnsariRockel2024.tawn_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.tawn_cdf_full

#print axioms Papers.AnsariRockel2024.tawn_zero_zero
#assert_standard_axioms Papers.AnsariRockel2024.tawn_zero_zero
#print axioms Papers.AnsariRockel2024.tawn_one_one
#assert_standard_axioms Papers.AnsariRockel2024.tawn_one_one
#print axioms Papers.AnsariRockel2024.tawn_zero_left
#assert_standard_axioms Papers.AnsariRockel2024.tawn_zero_left
#print axioms Papers.AnsariRockel2024.tawn_zero_right
#assert_standard_axioms Papers.AnsariRockel2024.tawn_zero_right
#print axioms Papers.AnsariRockel2024.tawn_shape_one
#assert_standard_axioms Papers.AnsariRockel2024.tawn_shape_one

#print axioms Papers.AnsariRockel2024.joe_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.joe_cdf_full

#print axioms Papers.AnsariRockel2024.joe_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.joe_tendsto_atTop
#print axioms Papers.AnsariRockel2024.joe_one
#assert_standard_axioms Papers.AnsariRockel2024.joe_one
#print axioms Papers.AnsariRockel2024.frank_positive_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_cdf_full

#print axioms Papers.AnsariRockel2024.frank_negative_cdf_reflected
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_cdf_reflected

#print axioms Papers.AnsariRockel2024.frank_negative_cdf_source
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_cdf_source

#print axioms Papers.AnsariRockel2024.frank_zero_cdf
#assert_standard_axioms Papers.AnsariRockel2024.frank_zero_cdf
#print axioms Papers.AnsariRockel2024.joe_tails
#assert_standard_axioms Papers.AnsariRockel2024.joe_tails

#print axioms Papers.AnsariRockel2024.nelsen8_not_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_pqd
#print axioms Papers.AnsariRockel2024.nelsen8_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_ci
#print axioms Papers.AnsariRockel2024.nelsen8_not_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_tp2_cdf
#print axioms Papers.AnsariRockel2024.nelsen8_not_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_mtp2_density
#print axioms Papers.AnsariRockel2024.nelsen8_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_cd
#print axioms Papers.AnsariRockel2024.nelsen8_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_cd_iff
#print axioms Papers.AnsariRockel2024.nelsen8_cd_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_cd_one
#print axioms Papers.AnsariRockel2024.nelsen8_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_lowerOrthant

#print axioms Papers.AnsariRockel2024.nelsen8_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_tails

#print axioms Papers.AnsariRockel2024.nelsen8_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen2_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_lowerOrthant
#print axioms Papers.AnsariRockel2024.nelsen2_not_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_pqd
#print axioms Papers.AnsariRockel2024.nelsen2_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_ci
#print axioms Papers.AnsariRockel2024.nelsen2_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_cd
#print axioms Papers.AnsariRockel2024.nelsen2_cd_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_cd_one
#print axioms Papers.AnsariRockel2024.nelsen2_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_cd_iff
#print axioms Papers.AnsariRockel2024.nelsen2_not_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_tp2_cdf
#print axioms Papers.AnsariRockel2024.nelsen2_not_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_mtp2_density
#print axioms Papers.AnsariRockel2024.nelsen2_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_tails

#print axioms Papers.AnsariRockel2024.nelsen2_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen2_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_cdf_full
#print axioms Papers.AnsariRockel2024.nelsen8_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_cdf_full
#print axioms Papers.AnsariRockel2024.genestGhoudi_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_cdf_full

#print axioms Papers.AnsariRockel2024.genestGhoudi_tails
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_tails

#print axioms Papers.AnsariRockel2024.genestGhoudi_not_pqd
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_not_pqd
#print axioms Papers.AnsariRockel2024.genestGhoudi_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_not_ci
#print axioms Papers.AnsariRockel2024.genestGhoudi_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_cd_iff
#print axioms Papers.AnsariRockel2024.genestGhoudi_not_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_not_tp2_cdf
#print axioms Papers.AnsariRockel2024.genestGhoudi_not_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_not_mtp2_density
#print axioms Papers.AnsariRockel2024.nelsen12_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen12_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen12_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_lowerOrthant

#print axioms Papers.AnsariRockel2024.nelsen12_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_tails
#print axioms Papers.AnsariRockel2024.nelsen14_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen14_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_tails

#print axioms Papers.AnsariRockel2024.nelsen14_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_tendsto_atTop

#print axioms Papers.AnsariRockel2024.genestGhoudi_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_tendsto_atTop
#print axioms Papers.AnsariRockel2024.nelsen2_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_one
#print axioms Papers.AnsariRockel2024.nelsen8_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_one
#print axioms Papers.AnsariRockel2024.genestGhoudi_one
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_one
#print axioms Papers.AnsariRockel2024.nelsen12_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_one
#print axioms Papers.AnsariRockel2024.nelsen14_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_one

#print axioms Papers.AnsariRockel2024.nelsen12_ci_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_ci_one
#print axioms Papers.AnsariRockel2024.nelsen14_ci_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_ci_one
#print axioms Papers.AnsariRockel2024.nelsen12_tp2_cdf_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_tp2_cdf_one
#print axioms Papers.AnsariRockel2024.nelsen14_tp2_cdf_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_tp2_cdf_one
#print axioms Papers.AnsariRockel2024.nelsen12_mtp2_density_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_mtp2_density_one
#print axioms Papers.AnsariRockel2024.nelsen14_mtp2_density_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_mtp2_density_one
#print axioms Papers.AnsariRockel2024.nelsen12_not_cd_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_not_cd_one
#print axioms Papers.AnsariRockel2024.nelsen14_not_cd_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_not_cd_one

#print axioms Papers.AnsariRockel2024.nelsen12_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_pqd
#print axioms Papers.AnsariRockel2024.nelsen12_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_not_cd
#print axioms Papers.AnsariRockel2024.nelsen14_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_not_cd

#print axioms Papers.AnsariRockel2024.nelsen14_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_pqd

#print axioms Papers.AnsariRockel2024.nelsen12_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_tp2_cdf
#print axioms Papers.AnsariRockel2024.nelsen14_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_tp2_cdf
#print axioms Papers.AnsariRockel2024.gumbel_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_tp2_cdf
#print axioms Papers.AnsariRockel2024.tawn_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.tawn_tp2_cdf
#print axioms Papers.AnsariRockel2024.marshallOlkin_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_tp2_cdf
#print axioms Papers.AnsariRockel2024.cuadrasAuge_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_tp2_cdf

#print axioms Papers.AnsariRockel2024.amh_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.amh_cdf_full

#print axioms Papers.AnsariRockel2024.amh_pqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_pqd_iff
#print axioms Papers.AnsariRockel2024.amh_nqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_nqd_iff

#print axioms Papers.AnsariRockel2024.amh_tails_lt_one
#assert_standard_axioms Papers.AnsariRockel2024.amh_tails_lt_one
#print axioms Papers.AnsariRockel2024.amh_tails_one
#assert_standard_axioms Papers.AnsariRockel2024.amh_tails_one

#print axioms Papers.AnsariRockel2024.amh_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.amh_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_ci_iff
#print axioms Papers.AnsariRockel2024.amh_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_cd_iff

#print axioms Papers.AnsariRockel2024.amh_schur_nonnegative_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_schur_nonnegative_iff
#print axioms Papers.AnsariRockel2024.amh_schur_nonpositive_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_schur_nonpositive_iff

#print axioms Papers.AnsariRockel2024.amh_zero
#assert_standard_axioms Papers.AnsariRockel2024.amh_zero

#print axioms Papers.AnsariRockel2024.amh_cdf_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_cdf_tp2_iff

#print axioms Papers.AnsariRockel2024.amh_negative_not_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.amh_negative_not_mtp2_density

#print axioms Papers.AnsariRockel2024.amh_zero_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.amh_zero_mtp2_density

#print axioms Papers.AnsariRockel2024.amh_one_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.amh_one_mtp2_density

#print axioms Papers.AnsariRockel2024.amh_density_formula
#assert_standard_axioms Papers.AnsariRockel2024.amh_density_formula

#print axioms Papers.AnsariRockel2024.amh_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_density_tp2_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_cdf
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_cdf

#print axioms Papers.AnsariRockel2024.gumbelBarnett_zero
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_zero

#print axioms Papers.AnsariRockel2024.gumbelBarnett_parameter_continuous
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_parameter_continuous

#print axioms Papers.AnsariRockel2024.gumbelBarnett_cd
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_cd

#print axioms Papers.AnsariRockel2024.gumbelBarnett_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_ci_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_density_tp2_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_schur_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_tails
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_tails

#print axioms Papers.AnsariRockel2024.gumbelBarnett_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_conditionalCDF

#print axioms Papers.AnsariRockel2024.gumbelBarnett_xi
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_xi

#print axioms Papers.AnsariRockel2024.gumbelBarnett_xi_zero
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_xi_zero

#print axioms Papers.AnsariRockel2024.frank_positive_tails
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_tails

#print axioms Papers.AnsariRockel2024.frank_negative_tails
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_tails

#print axioms Papers.AnsariRockel2024.frank_zero_tails
#assert_standard_axioms Papers.AnsariRockel2024.frank_zero_tails

#print axioms Papers.AnsariRockel2024.frank_positive_ci
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_ci

#print axioms Papers.AnsariRockel2024.frank_positive_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_not_cd

#print axioms Papers.AnsariRockel2024.frank_negative_cd
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_cd

#print axioms Papers.AnsariRockel2024.frank_negative_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_not_ci

#print axioms Papers.AnsariRockel2024.frank_positive_quadrant
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_quadrant

#print axioms Papers.AnsariRockel2024.frank_negative_quadrant
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_quadrant

#print axioms Papers.AnsariRockel2024.frank_negative_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_not_density_tp2

#print axioms Papers.AnsariRockel2024.frank_zero_ci_cd
#assert_standard_axioms Papers.AnsariRockel2024.frank_zero_ci_cd

#print axioms Papers.AnsariRockel2024.frank_positive_density
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_density

#print axioms Papers.AnsariRockel2024.frank_positive_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_density_tp2

#print axioms Papers.AnsariRockel2024.frank_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.frank_density_tp2_iff

#print axioms Papers.AnsariRockel2024.frank_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.frank_ci_iff

#print axioms Papers.AnsariRockel2024.frank_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.frank_cd_iff

#print axioms Papers.AnsariRockel2024.frank_cdf_lower_bound
#assert_standard_axioms Papers.AnsariRockel2024.frank_cdf_lower_bound

#print axioms Papers.AnsariRockel2024.frank_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.frank_tendsto_atTop

#print axioms Papers.AnsariRockel2024.frank_tendsto_atBot
#assert_standard_axioms Papers.AnsariRockel2024.frank_tendsto_atBot

#print axioms Papers.AnsariRockel2024.frankSigned_cdf_regular
#assert_standard_axioms Papers.AnsariRockel2024.frankSigned_cdf_regular

#print axioms Papers.AnsariRockel2024.frank_continuousAt_zero
#assert_standard_axioms Papers.AnsariRockel2024.frank_continuousAt_zero

#print axioms Papers.AnsariRockel2024.frank_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.frank_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen10_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_cdf

#print axioms Papers.AnsariRockel2024.nelsen10_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_zero

#print axioms Papers.AnsariRockel2024.nelsen10_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_one

#print axioms Papers.AnsariRockel2024.nelsen10_nqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_nqd

#print axioms Papers.AnsariRockel2024.nelsen10_pqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_pqd_iff

#print axioms Papers.AnsariRockel2024.nelsen10_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen10_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_density_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen10_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_tails

#print axioms Papers.AnsariRockel2024.nelsen10_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_cd

#print axioms Papers.AnsariRockel2024.nelsen10_continuousAt_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_continuousAt_zero

#print axioms Papers.AnsariRockel2024.nelsen10_cdf_crossing
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_cdf_crossing

#print axioms Papers.AnsariRockel2024.nelsen10_orthant_incomparable
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_orthant_incomparable

#print axioms Papers.AnsariRockel2024.nelsen10_schur_incomparable
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_schur_incomparable

#print axioms Papers.AnsariRockel2024.nelsen10_schurBoth_incomparable
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_schurBoth_incomparable

#print axioms Papers.AnsariRockel2024.nelsen11_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_cdf

#print axioms Papers.AnsariRockel2024.nelsen11_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_zero

#print axioms Papers.AnsariRockel2024.nelsen11_nqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_nqd

#print axioms Papers.AnsariRockel2024.nelsen11_pqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_pqd_iff

#print axioms Papers.AnsariRockel2024.nelsen11_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen11_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_density_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen11_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_tails

#print axioms Papers.AnsariRockel2024.nelsen11_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen11_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_cd

#print axioms Papers.AnsariRockel2024.nelsen11_lowerOrthant_antitone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_lowerOrthant_antitone

#print axioms Papers.AnsariRockel2024.nelsen11_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen13_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_cdf

#print axioms Papers.AnsariRockel2024.nelsen13_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_zero

#print axioms Papers.AnsariRockel2024.nelsen13_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_one

#print axioms Papers.AnsariRockel2024.nelsen13_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_tails

#print axioms Papers.AnsariRockel2024.nelsen13_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen13_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen13_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen13_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen13_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen13_density_tp2_requires_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_density_tp2_requires_one

#print axioms Papers.AnsariRockel2024.nelsen13_density_measure
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_density_measure

#print axioms Papers.AnsariRockel2024.nelsen13_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_density_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen12_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_ci

#print axioms Papers.AnsariRockel2024.nelsen14_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_ci

#print axioms Papers.AnsariRockel2024.nelsen12_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_schur_monotone

#print axioms Papers.AnsariRockel2024.gumbel_ci
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_ci

#print axioms Papers.AnsariRockel2024.gumbel_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_schur_monotone

#print axioms Papers.AnsariRockel2024.joe_ci
#assert_standard_axioms Papers.AnsariRockel2024.joe_ci

#print axioms Papers.AnsariRockel2024.joe_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.joe_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.joe_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.joe_schur_monotone

#print axioms Papers.AnsariRockel2024.joe_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.joe_toMeasure_density

#print axioms Papers.AnsariRockel2024.joe_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.joe_density_tp2

#print axioms Papers.AnsariRockel2024.gumbel_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_toMeasure_density

#print axioms Papers.AnsariRockel2024.gumbel_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen12_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen14_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen12_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_toMeasure_density

#print axioms Papers.AnsariRockel2024.nelsen14_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_toMeasure_density

#print axioms Papers.AnsariRockel2024.nelsen14_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen14_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen16_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen16_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_zero

#print axioms Papers.AnsariRockel2024.nelsen16_cdf_continuous_parameter
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_cdf_continuous_parameter

#print axioms Papers.AnsariRockel2024.nelsen16_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen16_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen16_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen16_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_tails

#print axioms Papers.AnsariRockel2024.nelsen16_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_ci

#print axioms Papers.AnsariRockel2024.nelsen16_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen16_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_toMeasure_density

#print axioms Papers.AnsariRockel2024.nelsen16_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen16_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen16_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_density_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen19_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_cdf

#print axioms Papers.AnsariRockel2024.nelsen19_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_zero

#print axioms Papers.AnsariRockel2024.nelsen19_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_ci

#print axioms Papers.AnsariRockel2024.nelsen19_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_tails

#print axioms Papers.AnsariRockel2024.nelsen19_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen19_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen19_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen19_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen19_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_toMeasure_density

#print axioms Papers.AnsariRockel2024.nelsen19_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen19_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen20_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_cdf

#print axioms Papers.AnsariRockel2024.nelsen20_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_zero

#print axioms Papers.AnsariRockel2024.nelsen20_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_ci

#print axioms Papers.AnsariRockel2024.nelsen20_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_tails

#print axioms Papers.AnsariRockel2024.nelsen20_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen20_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen20_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen20_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen20_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_toMeasure_density

#print axioms Papers.AnsariRockel2024.nelsen20_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen20_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen17_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen17_neg_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_neg_one


#print axioms Papers.AnsariRockel2024.nelsen17_isCI
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_isCI

#print axioms Papers.AnsariRockel2024.nelsen17_isCD
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_isCD

#print axioms Papers.AnsariRockel2024.nelsen17_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_tails

#print axioms Papers.AnsariRockel2024.nelsen17_isCI_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_isCI_iff

#print axioms Papers.AnsariRockel2024.nelsen17_isCD_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_isCD_iff

#print axioms Papers.AnsariRockel2024.nelsen17_isPQD_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_isPQD_iff

#print axioms Papers.AnsariRockel2024.nelsen17_isNQD_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_isNQD_iff

#print axioms Papers.AnsariRockel2024.nelsen17_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_toMeasure_density

#print axioms Papers.AnsariRockel2024.nelsen17_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_density_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen17_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen17_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen17_schur_antitone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_schur_antitone

#print axioms Papers.AnsariRockel2024.nelsen17_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen17_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen17_tendsto_atBot
#assert_standard_axioms Papers.AnsariRockel2024.nelsen17_tendsto_atBot

#print axioms Papers.AnsariRockel2024.nelsen21_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen21_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_one

#print axioms Papers.AnsariRockel2024.nelsen21_lowerTail
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_lowerTail

#print axioms Papers.AnsariRockel2024.nelsen21_upperTail
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_upperTail

#print axioms Papers.AnsariRockel2024.nelsen21_not_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_not_pqd

#print axioms Papers.AnsariRockel2024.nelsen21_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_not_ci

#print axioms Papers.AnsariRockel2024.nelsen21_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_not_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen21_isCD_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_isCD_iff

#print axioms Papers.AnsariRockel2024.nelsen21_isNQD_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_isNQD_iff

#print axioms Papers.AnsariRockel2024.nelsen21_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen21_tendsto_parameter
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_tendsto_parameter

#print axioms Papers.AnsariRockel2024.nelsen21_tendsto_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_tendsto_one

#print axioms Papers.AnsariRockel2024.nelsen21_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen21_not_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_not_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen21_not_schur_antitone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen21_not_schur_antitone

#print axioms Papers.AnsariRockel2024.nelsen18_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen18_cdf_of_lt_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_cdf_of_lt_one

#print axioms Papers.AnsariRockel2024.nelsen18_lowerTail
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_lowerTail

#print axioms Papers.AnsariRockel2024.nelsen18_upperTail
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_upperTail

#print axioms Papers.AnsariRockel2024.nelsen18_not_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_not_pqd

#print axioms Papers.AnsariRockel2024.nelsen18_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_not_ci

#print axioms Papers.AnsariRockel2024.nelsen18_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_not_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen18_not_nqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_not_nqd

#print axioms Papers.AnsariRockel2024.nelsen18_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_not_cd

#print axioms Papers.AnsariRockel2024.nelsen18_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen18_tendsto_parameter
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_tendsto_parameter

#print axioms Papers.AnsariRockel2024.nelsen18_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen18_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen22_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_zero

#print axioms Papers.AnsariRockel2024.nelsen22_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen22_cdf_printed
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_cdf_printed

#print axioms Papers.AnsariRockel2024.nelsen22_not_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_not_pqd

#print axioms Papers.AnsariRockel2024.nelsen22_isCI_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_isCI_iff

#print axioms Papers.AnsariRockel2024.nelsen22_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_density_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen22_lowerTail
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_lowerTail

#print axioms Papers.AnsariRockel2024.nelsen22_upperTail
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_upperTail

#print axioms Papers.AnsariRockel2024.nelsen22_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen22_tendsto_parameter
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_tendsto_parameter

#print axioms Papers.AnsariRockel2024.nelsen22_isCD
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_isCD

#print axioms Papers.AnsariRockel2024.nelsen22_isNQD
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_isNQD

#print axioms Papers.AnsariRockel2024.nelsen22_lowerOrthant_antitone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_lowerOrthant_antitone

#print axioms Papers.AnsariRockel2024.nelsen22_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen22_schur_monotone

#print axioms Papers.AnsariRockel2024.tawn_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.tawn_tendsto_atTop

#print axioms Papers.AnsariRockel2024.tawn_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.tawn_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.tawn_tendsto_parameter
#assert_standard_axioms Papers.AnsariRockel2024.tawn_tendsto_parameter

#print axioms Papers.AnsariRockel2024.tawn_one_one_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.tawn_one_one_density_tp2

#print axioms Papers.AnsariRockel2024.tawn_one_one_not_independence
#assert_standard_axioms Papers.AnsariRockel2024.tawn_one_one_not_independence

#print axioms Papers.AnsariRockel2024.tawn_printed_tp2_exclusion_false
#assert_standard_axioms Papers.AnsariRockel2024.tawn_printed_tp2_exclusion_false

#print axioms Papers.AnsariRockel2024.tawn_pickands
#assert_standard_axioms Papers.AnsariRockel2024.tawn_pickands

#print axioms Papers.AnsariRockel2024.gumbel_pickands
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_pickands

#print axioms Papers.AnsariRockel2024.marshallOlkin_pickands
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_pickands

#print axioms Papers.AnsariRockel2024.cuadrasAuge_pickands
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_pickands

#print axioms Papers.AnsariRockel2024.tawn_ci
#assert_standard_axioms Papers.AnsariRockel2024.tawn_ci

#print axioms Papers.AnsariRockel2024.tawn_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.tawn_schur_monotone

#print axioms Papers.AnsariRockel2024.maxProduct_independence_ci
#assert_standard_axioms Papers.AnsariRockel2024.maxProduct_independence_ci

#print axioms Papers.AnsariRockel2024.frank_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.frank_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.frank_schur_nonnegative
#assert_standard_axioms Papers.AnsariRockel2024.frank_schur_nonnegative

#print axioms Papers.AnsariRockel2024.frank_schur_nonpositive
#assert_standard_axioms Papers.AnsariRockel2024.frank_schur_nonpositive

#print axioms Papers.AnsariRockel2024.plackett_cdf
#assert_standard_axioms Papers.AnsariRockel2024.plackett_cdf

#print axioms Papers.AnsariRockel2024.plackett_one
#assert_standard_axioms Papers.AnsariRockel2024.plackett_one

#print axioms Papers.AnsariRockel2024.plackett_density
#assert_standard_axioms Papers.AnsariRockel2024.plackett_density

#print axioms Papers.AnsariRockel2024.plackett_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.plackett_ci_iff

#print axioms Papers.AnsariRockel2024.plackett_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.plackett_cd_iff

#print axioms Papers.AnsariRockel2024.plackett_pqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.plackett_pqd_iff

#print axioms Papers.AnsariRockel2024.plackett_nqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.plackett_nqd_iff

#print axioms Papers.AnsariRockel2024.plackett_tails
#assert_standard_axioms Papers.AnsariRockel2024.plackett_tails

#print axioms Papers.AnsariRockel2024.plackett_cdf_rationalized
#assert_standard_axioms Papers.AnsariRockel2024.plackett_cdf_rationalized

#print axioms Papers.AnsariRockel2024.plackett_tendsto_parameter
#assert_standard_axioms Papers.AnsariRockel2024.plackett_tendsto_parameter

#print axioms Papers.AnsariRockel2024.plackett_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.plackett_tendsto_zero

#print axioms Papers.AnsariRockel2024.plackett_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.plackett_tendsto_atTop

#print axioms Papers.AnsariRockel2024.plackett_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.plackett_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.plackett_schur_above_one
#assert_standard_axioms Papers.AnsariRockel2024.plackett_schur_above_one

#print axioms Papers.AnsariRockel2024.plackett_schur_below_one
#assert_standard_axioms Papers.AnsariRockel2024.plackett_schur_below_one

#print axioms Papers.AnsariRockel2024.plackett_density_tp2_necessary
#assert_standard_axioms Papers.AnsariRockel2024.plackett_density_tp2_necessary

#print axioms Papers.AnsariRockel2024.plackett_not_density_tp2_above_two
#assert_standard_axioms Papers.AnsariRockel2024.plackett_not_density_tp2_above_two

#print axioms Papers.AnsariRockel2024.plackett_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.plackett_density_tp2_iff

#print axioms Papers.AnsariRockel2024.plackett_spearmanRho
#assert_standard_axioms Papers.AnsariRockel2024.plackett_spearmanRho

#print axioms Papers.AnsariRockel2024.plackett_spearmanRho_one
#assert_standard_axioms Papers.AnsariRockel2024.plackett_spearmanRho_one

#print axioms Papers.AnsariRockel2024.plackett_printed_rho_false
#assert_standard_axioms Papers.AnsariRockel2024.plackett_printed_rho_false

#print axioms Papers.AnsariRockel2024.raftery_printed_cdf_not_copula
#assert_standard_axioms Papers.AnsariRockel2024.raftery_printed_cdf_not_copula

#print axioms Papers.AnsariRockel2024.raftery_zero_density
#assert_standard_axioms Papers.AnsariRockel2024.raftery_zero_density

#print axioms Papers.AnsariRockel2024.raftery_one_upperTail
#assert_standard_axioms Papers.AnsariRockel2024.raftery_one_upperTail

#print axioms Papers.AnsariRockel2024.raftery_cdf
#assert_standard_axioms Papers.AnsariRockel2024.raftery_cdf

#print axioms Papers.AnsariRockel2024.raftery_zero
#assert_standard_axioms Papers.AnsariRockel2024.raftery_zero

#print axioms Papers.AnsariRockel2024.raftery_one
#assert_standard_axioms Papers.AnsariRockel2024.raftery_one

#print axioms Papers.AnsariRockel2024.raftery_tails_lt_one
#assert_standard_axioms Papers.AnsariRockel2024.raftery_tails_lt_one

#print axioms Papers.AnsariRockel2024.raftery_tails_one
#assert_standard_axioms Papers.AnsariRockel2024.raftery_tails_one

#print axioms Papers.AnsariRockel2024.raftery_comonotonic_bounds
#assert_standard_axioms Papers.AnsariRockel2024.raftery_comonotonic_bounds

#print axioms Papers.AnsariRockel2024.raftery_tendsto_parameter
#assert_standard_axioms Papers.AnsariRockel2024.raftery_tendsto_parameter

#print axioms Papers.AnsariRockel2024.raftery_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.raftery_tendsto_zero

#print axioms Papers.AnsariRockel2024.raftery_tendsto_one
#assert_standard_axioms Papers.AnsariRockel2024.raftery_tendsto_one

#print axioms Papers.AnsariRockel2024.raftery_spearmanRho
#assert_standard_axioms Papers.AnsariRockel2024.raftery_spearmanRho

#print axioms Papers.AnsariRockel2024.raftery_density
#assert_standard_axioms Papers.AnsariRockel2024.raftery_density

#print axioms Papers.AnsariRockel2024.raftery_absolutelyContinuous_iff
#assert_standard_axioms Papers.AnsariRockel2024.raftery_absolutelyContinuous_iff

#print axioms Papers.AnsariRockel2024.raftery_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.raftery_density_tp2_iff

#print axioms Papers.AnsariRockel2024.raftery_ci
#assert_standard_axioms Papers.AnsariRockel2024.raftery_ci

#print axioms Papers.AnsariRockel2024.raftery_pqd
#assert_standard_axioms Papers.AnsariRockel2024.raftery_pqd

#print axioms Papers.AnsariRockel2024.raftery_nqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.raftery_nqd_iff

#print axioms Papers.AnsariRockel2024.raftery_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.raftery_cd_iff

#print axioms Papers.AnsariRockel2024.raftery_printed_tp2_exclusion_false
#assert_standard_axioms Papers.AnsariRockel2024.raftery_printed_tp2_exclusion_false

#print axioms Papers.AnsariRockel2024.raftery_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.raftery_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.raftery_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.raftery_schur_monotone

#print axioms Papers.AnsariRockel2024.raftery_kendallTau
#assert_standard_axioms Papers.AnsariRockel2024.raftery_kendallTau

#print axioms Papers.AnsariRockel2024.extremeValue_pickands_bounds
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_bounds

#print axioms Papers.AnsariRockel2024.extremeValue_log_homogeneous
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_log_homogeneous

#print axioms Papers.AnsariRockel2024.extremeValue_log_submodular
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_log_submodular

#print axioms Papers.AnsariRockel2024.extremeValue_log_increment_first
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_log_increment_first

#print axioms Papers.AnsariRockel2024.extremeValue_log_increment_second
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_log_increment_second

#print axioms Papers.AnsariRockel2024.extremeValue_log_section_convex
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_log_section_convex

#print axioms Papers.AnsariRockel2024.extremeValue_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_ci

#print axioms Papers.AnsariRockel2024.extremeValue_schur_iff_pickands
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_iff_pickands

#print axioms Papers.AnsariRockel2024.extremeValue_schur_first_iff_pickands
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_first_iff_pickands

#print axioms Papers.AnsariRockel2024.extremeValue_schur_second_iff_pickands
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_second_iff_pickands

#print axioms Papers.AnsariRockel2024.extremeValue_pickands_xi_mono
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_xi_mono

#print axioms Papers.AnsariRockel2024.extremeValue_pickands_real_coe
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_real_coe

#print axioms Papers.AnsariRockel2024.extremeValue_pickands_convex
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_convex

#print axioms Papers.AnsariRockel2024.amh_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.amh_conditionalCDF

#print axioms Papers.AnsariRockel2024.amh_chatterjeeXi
#assert_standard_axioms Papers.AnsariRockel2024.amh_chatterjeeXi

#print axioms Papers.AnsariRockel2024.amh_chatterjeeXi_zero
#assert_standard_axioms Papers.AnsariRockel2024.amh_chatterjeeXi_zero

#print axioms Papers.AnsariRockel2024.amh_chatterjeeXi_one
#assert_standard_axioms Papers.AnsariRockel2024.amh_chatterjeeXi_one

#print axioms Papers.AnsariRockel2024.amh_xi_bound_near_zero
#assert_standard_axioms Papers.AnsariRockel2024.amh_xi_bound_near_zero

#print axioms Papers.AnsariRockel2024.amh_xi_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.amh_xi_tendsto_zero

#print axioms Papers.AnsariRockel2024.amh_kendallTau
#assert_standard_axioms Papers.AnsariRockel2024.amh_kendallTau

#print axioms Papers.AnsariRockel2024.amh_kendallTau_zero
#assert_standard_axioms Papers.AnsariRockel2024.amh_kendallTau_zero

#print axioms Papers.AnsariRockel2024.amh_kendallTau_one
#assert_standard_axioms Papers.AnsariRockel2024.amh_kendallTau_one

#print axioms Papers.AnsariRockel2024.amh_spearmanRho_integral
#assert_standard_axioms Papers.AnsariRockel2024.amh_spearmanRho_integral

#print axioms Papers.AnsariRockel2024.amh_spearmanRho_zero
#assert_standard_axioms Papers.AnsariRockel2024.amh_spearmanRho_zero

#print axioms Papers.AnsariRockel2024.amh_spearmanRho
#assert_standard_axioms Papers.AnsariRockel2024.amh_spearmanRho

#print axioms Papers.AnsariRockel2024.amh_spearmanRho_one
#assert_standard_axioms Papers.AnsariRockel2024.amh_spearmanRho_one

#print axioms Papers.AnsariRockel2024.amh_spearmanRho_closed
#assert_standard_axioms Papers.AnsariRockel2024.amh_spearmanRho_closed

#print axioms Papers.AnsariRockel2024.frank_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.frank_conditionalCDF

#print axioms Papers.AnsariRockel2024.frank_kendallTau
#assert_standard_axioms Papers.AnsariRockel2024.frank_kendallTau

#print axioms Papers.AnsariRockel2024.frank_kendallTau_zero
#assert_standard_axioms Papers.AnsariRockel2024.frank_kendallTau_zero

#print axioms Papers.AnsariRockel2024.frank_debyeTwo_kernel_integral
#assert_standard_axioms Papers.AnsariRockel2024.frank_debyeTwo_kernel_integral

#print axioms Papers.AnsariRockel2024.frank_debyeOne_neg
#assert_standard_axioms Papers.AnsariRockel2024.frank_debyeOne_neg

#print axioms Papers.AnsariRockel2024.frank_debyeTwo_neg
#assert_standard_axioms Papers.AnsariRockel2024.frank_debyeTwo_neg

#print axioms Papers.AnsariRockel2024.frank_kendallTau_neg
#assert_standard_axioms Papers.AnsariRockel2024.frank_kendallTau_neg

#print axioms Papers.AnsariRockel2024.frank_spearmanRho_zero
#assert_standard_axioms Papers.AnsariRockel2024.frank_spearmanRho_zero

#print axioms Papers.AnsariRockel2024.frank_spearmanRho_neg
#assert_standard_axioms Papers.AnsariRockel2024.frank_spearmanRho_neg

#print axioms Papers.AnsariRockel2024.frank_spearmanRho
#assert_standard_axioms Papers.AnsariRockel2024.frank_spearmanRho

#print axioms Papers.AnsariRockel2024.clayton_positive_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_conditionalCDF

#print axioms Papers.AnsariRockel2024.clayton_positive_kendallTau
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_kendallTau

#print axioms Papers.AnsariRockel2024.clayton_zero_kendallTau
#assert_standard_axioms Papers.AnsariRockel2024.clayton_zero_kendallTau

#print axioms Papers.AnsariRockel2024.clayton_negative_one_kendallTau
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one_kendallTau

#print axioms Papers.AnsariRockel2024.clayton_negative_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_conditionalCDF

#print axioms Papers.AnsariRockel2024.clayton_negative_kendallTau
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_kendallTau

#print axioms Papers.AnsariRockel2024.clayton_positive_chatterjeeXi
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_chatterjeeXi

#print axioms Papers.AnsariRockel2024.gumbel_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_conditionalCDF

#print axioms Papers.AnsariRockel2024.gumbel_kendallTau_generator_integral
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_kendallTau_generator_integral

#print axioms Papers.AnsariRockel2024.gumbel_kendallTau
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_kendallTau

#print axioms Papers.AnsariRockel2024.gumbel_spearmanRho_ratio_integral
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_spearmanRho_ratio_integral

#print axioms Papers.AnsariRockel2024.gumbel_spearmanRho
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_spearmanRho
