import Papers.AnsariRockel2024.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockel2024.clayton_positive_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_cdf
#print axioms Papers.AnsariRockel2024.clayton_cdf_positive_eq_analytic
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_positive_eq_analytic

#print axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_first
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_first

#print axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_second
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_second

#print axioms Papers.AnsariRockel2024.clayton_mixed_derivative_eq_densityFormula
#assert_standard_axioms Papers.AnsariRockel2024.clayton_mixed_derivative_eq_densityFormula

#print axioms Papers.AnsariRockel2024.clayton_density_formula_integral_second
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_integral_second

#print axioms Papers.AnsariRockel2024.clayton_cdf_formula_integral_first
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_formula_integral_first

#print axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle

#print axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_densityFormula_positive_rectangle_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_densityFormula_positive_rectangle_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_withDensity_positive_rectangle_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_positive_rectangle_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_withDensity_axis_zero
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_axis_zero

#print axioms Papers.AnsariRockel2024.clayton_withDensity_positive_lowerOrthant_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_positive_lowerOrthant_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_withDensity_lowerOrthant_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_lowerOrthant_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_toMeasure_eq_withDensity_positive
#assert_standard_axioms Papers.AnsariRockel2024.clayton_toMeasure_eq_withDensity_positive

#print axioms Papers.AnsariRockel2024.clayton_positive_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_density_tp2

#print axioms Papers.AnsariRockel2024.clayton_positive_absolutelyContinuous
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_absolutelyContinuous

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_bounds
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_bounds

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_tendsto_one
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_tendsto_one

#print axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_cdf_bounds
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_cdf_bounds

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_rectangle_tendsto_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_rectangle_tendsto_cdf

#print axioms Papers.AnsariRockel2024.clayton_negative_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_cdf
#print axioms Papers.AnsariRockel2024.clayton_positive_zero_axes
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_zero_axes
#print axioms Papers.AnsariRockel2024.clayton_negative_zero_axes
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_zero_axes
#print axioms Papers.AnsariRockel2024.clayton_one_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_one_cdf

#print axioms Papers.AnsariRockel2024.clayton_zero_ci_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_zero_ci_cd
#print axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_one_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one_cd

#print axioms Papers.AnsariRockel2024.clayton_negative_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_cd

#print axioms Papers.AnsariRockel2024.clayton_negative_nqd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_nqd

#print axioms Papers.AnsariRockel2024.clayton_positive_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_not_cd
#print axioms Papers.AnsariRockel2024.clayton_negative_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_not_ci

#print axioms Papers.AnsariRockel2024.clayton_positive_ci
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_ci

#print axioms Papers.AnsariRockel2024.clayton_positive_pqd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_pqd

#print axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_one
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one
#print axioms Papers.AnsariRockel2024.clayton_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.clayton_tendsto_zero
#print axioms Papers.AnsariRockel2024.clayton_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.clayton_tendsto_atTop

#print axioms Papers.AnsariRockel2024.classical_representation
#assert_standard_axioms Papers.AnsariRockel2024.classical_representation

#print axioms Papers.AnsariRockel2024.fgm_cdf
#assert_standard_axioms Papers.AnsariRockel2024.fgm_cdf

#print axioms Papers.AnsariRockel2024.xi_derivative_formula
#assert_standard_axioms Papers.AnsariRockel2024.xi_derivative_formula

#print axioms Papers.AnsariRockel2024.fgm_rho
#assert_standard_axioms Papers.AnsariRockel2024.fgm_rho

#print axioms Papers.AnsariRockel2024.fgm_tau
#assert_standard_axioms Papers.AnsariRockel2024.fgm_tau

#print axioms Papers.AnsariRockel2024.fgm_xi
#assert_standard_axioms Papers.AnsariRockel2024.fgm_xi

#print axioms Papers.AnsariRockel2024.frechet_rho
#assert_standard_axioms Papers.AnsariRockel2024.frechet_rho

#print axioms Papers.AnsariRockel2024.frechet_tau
#assert_standard_axioms Papers.AnsariRockel2024.frechet_tau

#print axioms Papers.AnsariRockel2024.frechet_xi
#assert_standard_axioms Papers.AnsariRockel2024.frechet_xi

#print axioms Papers.AnsariRockel2024.mardia_rho
#assert_standard_axioms Papers.AnsariRockel2024.mardia_rho

#print axioms Papers.AnsariRockel2024.mardia_tau
#assert_standard_axioms Papers.AnsariRockel2024.mardia_tau

#print axioms Papers.AnsariRockel2024.mardia_xi
#assert_standard_axioms Papers.AnsariRockel2024.mardia_xi

#print axioms Papers.AnsariRockel2024.fgm_ci
#assert_standard_axioms Papers.AnsariRockel2024.fgm_ci

#print axioms Papers.AnsariRockel2024.fgm_cd
#assert_standard_axioms Papers.AnsariRockel2024.fgm_cd

#print axioms Papers.AnsariRockel2024.fgm_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.fgm_lowerOrthant

#print axioms Papers.AnsariRockel2024.fgm_tails
#assert_standard_axioms Papers.AnsariRockel2024.fgm_tails

#print axioms Papers.AnsariRockel2024.frechet_tails
#assert_standard_axioms Papers.AnsariRockel2024.frechet_tails

#print axioms Papers.AnsariRockel2024.mardia_tails
#assert_standard_axioms Papers.AnsariRockel2024.mardia_tails

#print axioms Papers.AnsariRockel2024.fgm_density
#assert_standard_axioms Papers.AnsariRockel2024.fgm_density

#print axioms Papers.AnsariRockel2024.fgm_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.fgm_density_tp2_iff

#print axioms Papers.AnsariRockel2024.fgm_has_tp2_density
#assert_standard_axioms Papers.AnsariRockel2024.fgm_has_tp2_density

#print axioms Papers.AnsariRockel2024.nelsen7_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_cdf

#print axioms Papers.AnsariRockel2024.nelsen7_endpoints
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_endpoints

#print axioms Papers.AnsariRockel2024.nelsen7_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_cd

#print axioms Papers.AnsariRockel2024.nelsen7_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.nelsen7_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tails

#print axioms Papers.AnsariRockel2024.gumbel_tails
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_tails

#print axioms Papers.AnsariRockel2024.marshallOlkin_tails
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_tails

#print axioms Papers.AnsariRockel2024.cuadrasAuge_tails
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_tails

#print axioms Papers.AnsariRockel2024.tawn_tails
#assert_standard_axioms Papers.AnsariRockel2024.tawn_tails

#print axioms Papers.AnsariRockel2024.fgm_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.fgm_schur_iff

#print axioms Papers.AnsariRockel2024.frechet_parameter_order
#assert_standard_axioms Papers.AnsariRockel2024.frechet_parameter_order

#print axioms Papers.AnsariRockel2024.frechet_order_counterexample
#assert_standard_axioms Papers.AnsariRockel2024.frechet_order_counterexample

#print axioms Papers.AnsariRockel2024.frechet_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_ci_iff

#print axioms Papers.AnsariRockel2024.frechet_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_cd_iff

#print axioms Papers.AnsariRockel2024.frechet_absolutelyContinuous_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_absolutelyContinuous_iff

#print axioms Papers.AnsariRockel2024.frechet_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_density_tp2_iff

#print axioms Papers.AnsariRockel2024.mardia_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_ci_iff

#print axioms Papers.AnsariRockel2024.mardia_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_cd_iff

#print axioms Papers.AnsariRockel2024.mardia_absolutelyContinuous_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_absolutelyContinuous_iff

#print axioms Papers.AnsariRockel2024.mardia_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_density_tp2_iff

#print axioms Papers.AnsariRockel2024.mardia_not_lowerOrthant_ordered
#assert_standard_axioms Papers.AnsariRockel2024.mardia_not_lowerOrthant_ordered

#print axioms Papers.AnsariRockel2024.nelsen7_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_conditionalCDF

#print axioms Papers.AnsariRockel2024.nelsen7_derivative
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_derivative

#print axioms Papers.AnsariRockel2024.nelsen7_xi
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_xi

#print axioms Papers.AnsariRockel2024.nelsen7_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen7_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_schur_iff

#print axioms Papers.AnsariRockel2024.survival_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.survival_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.survival_cis_iff
#assert_standard_axioms Papers.AnsariRockel2024.survival_cis_iff

#print axioms Papers.AnsariRockel2024.survival_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.survival_schur_iff

#print axioms Papers.AnsariRockel2024.concordance_coefficients_mono
#assert_standard_axioms Papers.AnsariRockel2024.concordance_coefficients_mono

#print axioms Papers.AnsariRockel2024.schur_xi_mono
#assert_standard_axioms Papers.AnsariRockel2024.schur_xi_mono

#print axioms Papers.AnsariRockel2024.lower_tail_mono
#assert_standard_axioms Papers.AnsariRockel2024.lower_tail_mono

#print axioms Papers.AnsariRockel2024.upper_tail_mono
#assert_standard_axioms Papers.AnsariRockel2024.upper_tail_mono

#print axioms Papers.AnsariRockel2024.schur_below_cis
#assert_standard_axioms Papers.AnsariRockel2024.schur_below_cis

#print axioms Papers.AnsariRockel2024.schur_below_cds
#assert_standard_axioms Papers.AnsariRockel2024.schur_below_cds

#print axioms Papers.AnsariRockel2024.cis_schur_iff_orthant
#assert_standard_axioms Papers.AnsariRockel2024.cis_schur_iff_orthant
#print axioms Papers.AnsariRockel2024.cds_schur_iff_reverse_orthant
#assert_standard_axioms Papers.AnsariRockel2024.cds_schur_iff_reverse_orthant

#print axioms Papers.AnsariRockel2024.extremeValue_schur_first_iff_pickands_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_first_iff_pickands_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_schur_second_iff_pickands_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_second_iff_pickands_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_tail_mono
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_tail_mono
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_concordance_mono
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_concordance_mono
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_xi_mono_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_xi_mono_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_schur_iff_pickands_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_iff_pickands_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_order
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_order
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_representation
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_representation
#print axioms Papers.AnsariRockel2024.marshallOlkin_rho
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_rho

#print axioms Papers.AnsariRockel2024.marshallOlkin_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_conditionalCDF

#print axioms Papers.AnsariRockel2024.marshallOlkin_xi
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_xi

#print axioms Papers.AnsariRockel2024.marshallOlkin_tau
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_tau

#print axioms Papers.AnsariRockel2024.marshallOlkin_cdf
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_cdf
#print axioms Papers.AnsariRockel2024.marshallOlkin_ci
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_ci
#print axioms Papers.AnsariRockel2024.marshallOlkin_orthant_mono
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_orthant_mono
#print axioms Papers.AnsariRockel2024.marshallOlkin_schur_mono
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_schur_mono
#print axioms Papers.AnsariRockel2024.cuadrasAuge_ci
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_ci
#print axioms Papers.AnsariRockel2024.cuadrasAuge_orthant_mono
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_orthant_mono
#print axioms Papers.AnsariRockel2024.cuadrasAuge_schur_mono
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_schur_mono

#print axioms Papers.AnsariRockel2024.cuadrasAuge_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_conditionalCDF
#print axioms Papers.AnsariRockel2024.cuadrasAuge_rho
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_rho
#print axioms Papers.AnsariRockel2024.cuadrasAuge_xi
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_xi

#print axioms Papers.AnsariRockel2024.cuadrasAuge_tau
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_tau

#print axioms Papers.AnsariRockel2024.marshallOlkin_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_density_tp2
#print axioms Papers.AnsariRockel2024.marshallOlkin_absolutelyContinuous
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_absolutelyContinuous
#print axioms Papers.AnsariRockel2024.marshallOlkin_independence_axes
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_independence_axes
#print axioms Papers.AnsariRockel2024.cuadrasAuge_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_density_tp2
#print axioms Papers.AnsariRockel2024.cuadrasAuge_absolutelyContinuous
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_absolutelyContinuous

#print axioms Papers.AnsariRockel2024.clayton_positive_cdf_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_cdf_tp2
#print axioms Papers.AnsariRockel2024.clayton_zero_cdf_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_zero_cdf_tp2
#print axioms Papers.AnsariRockel2024.clayton_negative_not_cdf_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_not_cdf_tp2

#print axioms Papers.AnsariRockel2024.clayton_negative_one_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one_not_density_tp2

#print axioms Papers.AnsariRockel2024.hasMTP2Density_isPQD
#assert_standard_axioms Papers.AnsariRockel2024.hasMTP2Density_isPQD

#print axioms Papers.AnsariRockel2024.clayton_negative_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_not_density_tp2

#print axioms Papers.AnsariRockel2024.isCD_eq_independence_of_hasMTP2Density
#assert_standard_axioms Papers.AnsariRockel2024.isCD_eq_independence_of_hasMTP2Density

#print axioms Papers.AnsariRockel2024.isCD_eq_independence_of_isTP2CDF
#assert_standard_axioms Papers.AnsariRockel2024.isCD_eq_independence_of_isTP2CDF

#print axioms Papers.AnsariRockel2024.nelsen7_cdf_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_cdf_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen7_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_density_tp2_iff

#print axioms Papers.AnsariRockel2024.fgm_hasMTP2Density_iff
#assert_standard_axioms Papers.AnsariRockel2024.fgm_hasMTP2Density_iff

#print axioms Papers.AnsariRockel2024.nelsen7_integral_cdf_first
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_integral_cdf_first
#print axioms Papers.AnsariRockel2024.nelsen7_rho_integral
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_rho_integral
#print axioms Papers.AnsariRockel2024.nelsen7_rho_interior
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_rho_interior
#print axioms Papers.AnsariRockel2024.nelsen7_rho
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_rho
#print axioms Papers.AnsariRockel2024.nelsen7_tau_rho
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tau_rho
#print axioms Papers.AnsariRockel2024.nelsen7_tau_interior
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tau_interior
#print axioms Papers.AnsariRockel2024.nelsen7_tau
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tau
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_expanded
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_expanded
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_formula
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_formula
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_candidate_zero
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_identity_false_half
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_identity_false_half
#print axioms Papers.AnsariRockel2024.nelsen7_printed_xi_identity_false
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_printed_xi_identity_false

#print axioms Papers.AnsariRockel2024.gumbel_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_cdf_full

#print axioms Papers.AnsariRockel2024.gumbel_one
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_one

#print axioms Papers.AnsariRockel2024.gumbel_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_tendsto_atTop

#print axioms Papers.AnsariRockel2024.gumbel_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_lowerOrthant
#print axioms Papers.AnsariRockel2024.tawn_cdf_positive
#assert_standard_axioms Papers.AnsariRockel2024.tawn_cdf_positive
#print axioms Papers.AnsariRockel2024.tawn_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.tawn_cdf_full

#print axioms Papers.AnsariRockel2024.tawn_zero_zero
#assert_standard_axioms Papers.AnsariRockel2024.tawn_zero_zero
#print axioms Papers.AnsariRockel2024.tawn_one_one
#assert_standard_axioms Papers.AnsariRockel2024.tawn_one_one
#print axioms Papers.AnsariRockel2024.tawn_zero_left
#assert_standard_axioms Papers.AnsariRockel2024.tawn_zero_left
#print axioms Papers.AnsariRockel2024.tawn_zero_right
#assert_standard_axioms Papers.AnsariRockel2024.tawn_zero_right
#print axioms Papers.AnsariRockel2024.tawn_shape_one
#assert_standard_axioms Papers.AnsariRockel2024.tawn_shape_one

#print axioms Papers.AnsariRockel2024.joe_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.joe_cdf_full

#print axioms Papers.AnsariRockel2024.joe_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.joe_tendsto_atTop
#print axioms Papers.AnsariRockel2024.joe_one
#assert_standard_axioms Papers.AnsariRockel2024.joe_one
#print axioms Papers.AnsariRockel2024.frank_positive_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_cdf_full

#print axioms Papers.AnsariRockel2024.frank_negative_cdf_reflected
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_cdf_reflected

#print axioms Papers.AnsariRockel2024.frank_negative_cdf_source
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_cdf_source

#print axioms Papers.AnsariRockel2024.frank_zero_cdf
#assert_standard_axioms Papers.AnsariRockel2024.frank_zero_cdf
#print axioms Papers.AnsariRockel2024.joe_tails
#assert_standard_axioms Papers.AnsariRockel2024.joe_tails

#print axioms Papers.AnsariRockel2024.nelsen8_not_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_pqd
#print axioms Papers.AnsariRockel2024.nelsen8_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_ci
#print axioms Papers.AnsariRockel2024.nelsen8_not_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_tp2_cdf
#print axioms Papers.AnsariRockel2024.nelsen8_not_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_mtp2_density
#print axioms Papers.AnsariRockel2024.nelsen8_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_not_cd
#print axioms Papers.AnsariRockel2024.nelsen8_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_cd_iff
#print axioms Papers.AnsariRockel2024.nelsen8_cd_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_cd_one
#print axioms Papers.AnsariRockel2024.nelsen8_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_lowerOrthant

#print axioms Papers.AnsariRockel2024.nelsen8_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_tails

#print axioms Papers.AnsariRockel2024.nelsen8_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen2_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_lowerOrthant
#print axioms Papers.AnsariRockel2024.nelsen2_not_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_pqd
#print axioms Papers.AnsariRockel2024.nelsen2_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_ci
#print axioms Papers.AnsariRockel2024.nelsen2_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_cd
#print axioms Papers.AnsariRockel2024.nelsen2_cd_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_cd_one
#print axioms Papers.AnsariRockel2024.nelsen2_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_cd_iff
#print axioms Papers.AnsariRockel2024.nelsen2_not_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_tp2_cdf
#print axioms Papers.AnsariRockel2024.nelsen2_not_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_not_mtp2_density
#print axioms Papers.AnsariRockel2024.nelsen2_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_tails

#print axioms Papers.AnsariRockel2024.nelsen2_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen2_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_cdf_full
#print axioms Papers.AnsariRockel2024.nelsen8_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_cdf_full
#print axioms Papers.AnsariRockel2024.genestGhoudi_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_cdf_full

#print axioms Papers.AnsariRockel2024.genestGhoudi_tails
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_tails

#print axioms Papers.AnsariRockel2024.genestGhoudi_not_pqd
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_not_pqd
#print axioms Papers.AnsariRockel2024.genestGhoudi_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_not_ci
#print axioms Papers.AnsariRockel2024.genestGhoudi_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_cd_iff
#print axioms Papers.AnsariRockel2024.genestGhoudi_not_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_not_tp2_cdf
#print axioms Papers.AnsariRockel2024.genestGhoudi_not_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_not_mtp2_density
#print axioms Papers.AnsariRockel2024.nelsen12_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen12_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen12_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_lowerOrthant

#print axioms Papers.AnsariRockel2024.nelsen12_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_tails
#print axioms Papers.AnsariRockel2024.nelsen14_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen14_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_tails

#print axioms Papers.AnsariRockel2024.nelsen14_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_tendsto_atTop

#print axioms Papers.AnsariRockel2024.genestGhoudi_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_tendsto_atTop
#print axioms Papers.AnsariRockel2024.nelsen2_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen2_one
#print axioms Papers.AnsariRockel2024.nelsen8_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen8_one
#print axioms Papers.AnsariRockel2024.genestGhoudi_one
#assert_standard_axioms Papers.AnsariRockel2024.genestGhoudi_one
#print axioms Papers.AnsariRockel2024.nelsen12_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_one
#print axioms Papers.AnsariRockel2024.nelsen14_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_one

#print axioms Papers.AnsariRockel2024.nelsen12_ci_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_ci_one
#print axioms Papers.AnsariRockel2024.nelsen14_ci_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_ci_one
#print axioms Papers.AnsariRockel2024.nelsen12_tp2_cdf_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_tp2_cdf_one
#print axioms Papers.AnsariRockel2024.nelsen14_tp2_cdf_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_tp2_cdf_one
#print axioms Papers.AnsariRockel2024.nelsen12_mtp2_density_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_mtp2_density_one
#print axioms Papers.AnsariRockel2024.nelsen14_mtp2_density_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_mtp2_density_one
#print axioms Papers.AnsariRockel2024.nelsen12_not_cd_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_not_cd_one
#print axioms Papers.AnsariRockel2024.nelsen14_not_cd_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_not_cd_one

#print axioms Papers.AnsariRockel2024.nelsen12_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_pqd
#print axioms Papers.AnsariRockel2024.nelsen12_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_not_cd
#print axioms Papers.AnsariRockel2024.nelsen14_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_not_cd

#print axioms Papers.AnsariRockel2024.nelsen14_pqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_pqd

#print axioms Papers.AnsariRockel2024.nelsen12_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_tp2_cdf
#print axioms Papers.AnsariRockel2024.nelsen14_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_tp2_cdf
#print axioms Papers.AnsariRockel2024.gumbel_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_tp2_cdf
#print axioms Papers.AnsariRockel2024.tawn_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.tawn_tp2_cdf
#print axioms Papers.AnsariRockel2024.marshallOlkin_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_tp2_cdf
#print axioms Papers.AnsariRockel2024.cuadrasAuge_tp2_cdf
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_tp2_cdf

#print axioms Papers.AnsariRockel2024.amh_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.amh_cdf_full

#print axioms Papers.AnsariRockel2024.amh_pqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_pqd_iff
#print axioms Papers.AnsariRockel2024.amh_nqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_nqd_iff

#print axioms Papers.AnsariRockel2024.amh_tails_lt_one
#assert_standard_axioms Papers.AnsariRockel2024.amh_tails_lt_one
#print axioms Papers.AnsariRockel2024.amh_tails_one
#assert_standard_axioms Papers.AnsariRockel2024.amh_tails_one

#print axioms Papers.AnsariRockel2024.amh_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.amh_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_ci_iff
#print axioms Papers.AnsariRockel2024.amh_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_cd_iff

#print axioms Papers.AnsariRockel2024.amh_schur_nonnegative_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_schur_nonnegative_iff
#print axioms Papers.AnsariRockel2024.amh_schur_nonpositive_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_schur_nonpositive_iff

#print axioms Papers.AnsariRockel2024.amh_zero
#assert_standard_axioms Papers.AnsariRockel2024.amh_zero

#print axioms Papers.AnsariRockel2024.amh_cdf_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_cdf_tp2_iff

#print axioms Papers.AnsariRockel2024.amh_negative_not_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.amh_negative_not_mtp2_density

#print axioms Papers.AnsariRockel2024.amh_zero_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.amh_zero_mtp2_density

#print axioms Papers.AnsariRockel2024.amh_one_mtp2_density
#assert_standard_axioms Papers.AnsariRockel2024.amh_one_mtp2_density

#print axioms Papers.AnsariRockel2024.amh_density_formula
#assert_standard_axioms Papers.AnsariRockel2024.amh_density_formula

#print axioms Papers.AnsariRockel2024.amh_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.amh_density_tp2_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_cdf
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_cdf

#print axioms Papers.AnsariRockel2024.gumbelBarnett_zero
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_zero

#print axioms Papers.AnsariRockel2024.gumbelBarnett_parameter_continuous
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_parameter_continuous

#print axioms Papers.AnsariRockel2024.gumbelBarnett_cd
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_cd

#print axioms Papers.AnsariRockel2024.gumbelBarnett_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_ci_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_density_tp2_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_schur_iff

#print axioms Papers.AnsariRockel2024.gumbelBarnett_tails
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_tails

#print axioms Papers.AnsariRockel2024.gumbelBarnett_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_conditionalCDF

#print axioms Papers.AnsariRockel2024.gumbelBarnett_xi
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_xi

#print axioms Papers.AnsariRockel2024.gumbelBarnett_xi_zero
#assert_standard_axioms Papers.AnsariRockel2024.gumbelBarnett_xi_zero

#print axioms Papers.AnsariRockel2024.frank_positive_tails
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_tails

#print axioms Papers.AnsariRockel2024.frank_negative_tails
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_tails

#print axioms Papers.AnsariRockel2024.frank_zero_tails
#assert_standard_axioms Papers.AnsariRockel2024.frank_zero_tails

#print axioms Papers.AnsariRockel2024.frank_positive_ci
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_ci

#print axioms Papers.AnsariRockel2024.frank_positive_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_not_cd

#print axioms Papers.AnsariRockel2024.frank_negative_cd
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_cd

#print axioms Papers.AnsariRockel2024.frank_negative_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_not_ci

#print axioms Papers.AnsariRockel2024.frank_positive_quadrant
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_quadrant

#print axioms Papers.AnsariRockel2024.frank_negative_quadrant
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_quadrant

#print axioms Papers.AnsariRockel2024.frank_negative_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.frank_negative_not_density_tp2

#print axioms Papers.AnsariRockel2024.frank_zero_ci_cd
#assert_standard_axioms Papers.AnsariRockel2024.frank_zero_ci_cd

#print axioms Papers.AnsariRockel2024.frank_positive_density
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_density

#print axioms Papers.AnsariRockel2024.frank_positive_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.frank_positive_density_tp2

#print axioms Papers.AnsariRockel2024.frank_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.frank_density_tp2_iff

#print axioms Papers.AnsariRockel2024.frank_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.frank_ci_iff

#print axioms Papers.AnsariRockel2024.frank_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.frank_cd_iff

#print axioms Papers.AnsariRockel2024.frank_cdf_lower_bound
#assert_standard_axioms Papers.AnsariRockel2024.frank_cdf_lower_bound

#print axioms Papers.AnsariRockel2024.frank_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.frank_tendsto_atTop

#print axioms Papers.AnsariRockel2024.frank_tendsto_atBot
#assert_standard_axioms Papers.AnsariRockel2024.frank_tendsto_atBot

#print axioms Papers.AnsariRockel2024.frankSigned_cdf_regular
#assert_standard_axioms Papers.AnsariRockel2024.frankSigned_cdf_regular

#print axioms Papers.AnsariRockel2024.frank_continuousAt_zero
#assert_standard_axioms Papers.AnsariRockel2024.frank_continuousAt_zero

#print axioms Papers.AnsariRockel2024.frank_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.frank_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen10_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_cdf

#print axioms Papers.AnsariRockel2024.nelsen10_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_zero

#print axioms Papers.AnsariRockel2024.nelsen10_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_one

#print axioms Papers.AnsariRockel2024.nelsen10_nqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_nqd

#print axioms Papers.AnsariRockel2024.nelsen10_pqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_pqd_iff

#print axioms Papers.AnsariRockel2024.nelsen10_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen10_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_density_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen10_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_tails

#print axioms Papers.AnsariRockel2024.nelsen10_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_cd

#print axioms Papers.AnsariRockel2024.nelsen10_continuousAt_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_continuousAt_zero

#print axioms Papers.AnsariRockel2024.nelsen10_cdf_crossing
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_cdf_crossing

#print axioms Papers.AnsariRockel2024.nelsen10_orthant_incomparable
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_orthant_incomparable

#print axioms Papers.AnsariRockel2024.nelsen10_schur_incomparable
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_schur_incomparable

#print axioms Papers.AnsariRockel2024.nelsen10_schurBoth_incomparable
#assert_standard_axioms Papers.AnsariRockel2024.nelsen10_schurBoth_incomparable

#print axioms Papers.AnsariRockel2024.nelsen11_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_cdf

#print axioms Papers.AnsariRockel2024.nelsen11_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_zero

#print axioms Papers.AnsariRockel2024.nelsen11_nqd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_nqd

#print axioms Papers.AnsariRockel2024.nelsen11_pqd_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_pqd_iff

#print axioms Papers.AnsariRockel2024.nelsen11_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen11_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_density_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen11_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_tails

#print axioms Papers.AnsariRockel2024.nelsen11_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen11_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_cd

#print axioms Papers.AnsariRockel2024.nelsen11_lowerOrthant_antitone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_lowerOrthant_antitone

#print axioms Papers.AnsariRockel2024.nelsen11_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen11_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen13_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_cdf

#print axioms Papers.AnsariRockel2024.nelsen13_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_zero

#print axioms Papers.AnsariRockel2024.nelsen13_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_one

#print axioms Papers.AnsariRockel2024.nelsen13_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_tails

#print axioms Papers.AnsariRockel2024.nelsen13_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen13_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen13_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen13_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen13_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen13_density_tp2_requires_one
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_density_tp2_requires_one

#print axioms Papers.AnsariRockel2024.nelsen13_density_measure
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_density_measure

#print axioms Papers.AnsariRockel2024.nelsen13_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen13_density_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen12_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_ci

#print axioms Papers.AnsariRockel2024.nelsen14_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_ci

#print axioms Papers.AnsariRockel2024.nelsen12_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_schur_monotone

#print axioms Papers.AnsariRockel2024.gumbel_ci
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_ci

#print axioms Papers.AnsariRockel2024.gumbel_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_schur_monotone

#print axioms Papers.AnsariRockel2024.joe_ci
#assert_standard_axioms Papers.AnsariRockel2024.joe_ci

#print axioms Papers.AnsariRockel2024.joe_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.joe_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.joe_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.joe_schur_monotone

#print axioms Papers.AnsariRockel2024.joe_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.joe_toMeasure_density

#print axioms Papers.AnsariRockel2024.joe_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.joe_density_tp2

#print axioms Papers.AnsariRockel2024.gumbel_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_toMeasure_density

#print axioms Papers.AnsariRockel2024.gumbel_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen12_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen14_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_density_tp2

#print axioms Papers.AnsariRockel2024.nelsen12_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen12_toMeasure_density

#print axioms Papers.AnsariRockel2024.nelsen14_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_toMeasure_density

#print axioms Papers.AnsariRockel2024.nelsen14_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen14_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen14_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen16_cdf_full
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_cdf_full

#print axioms Papers.AnsariRockel2024.nelsen16_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_zero

#print axioms Papers.AnsariRockel2024.nelsen16_cdf_continuous_parameter
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_cdf_continuous_parameter

#print axioms Papers.AnsariRockel2024.nelsen16_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_tendsto_zero

#print axioms Papers.AnsariRockel2024.nelsen16_lowerOrthant_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_lowerOrthant_monotone

#print axioms Papers.AnsariRockel2024.nelsen16_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_tendsto_atTop

#print axioms Papers.AnsariRockel2024.nelsen16_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_tails

#print axioms Papers.AnsariRockel2024.nelsen16_ci
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_ci

#print axioms Papers.AnsariRockel2024.nelsen16_schur_monotone
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_schur_monotone

#print axioms Papers.AnsariRockel2024.nelsen16_toMeasure_density
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_toMeasure_density

#print axioms Papers.AnsariRockel2024.nelsen16_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.nelsen16_density_tp2
