import Papers.AnsariRockel2024.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.AnsariRockel2024.clayton_positive_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_cdf
#print axioms Papers.AnsariRockel2024.clayton_cdf_positive_eq_analytic
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_positive_eq_analytic

#print axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_first
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_first

#print axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_second
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_formula_hasDerivAt_second

#print axioms Papers.AnsariRockel2024.clayton_mixed_derivative_eq_densityFormula
#assert_standard_axioms Papers.AnsariRockel2024.clayton_mixed_derivative_eq_densityFormula

#print axioms Papers.AnsariRockel2024.clayton_density_formula_integral_second
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_integral_second

#print axioms Papers.AnsariRockel2024.clayton_cdf_formula_integral_first
#assert_standard_axioms Papers.AnsariRockel2024.clayton_cdf_formula_integral_first

#print axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle

#print axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_densityFormula_positive_rectangle_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_densityFormula_positive_rectangle_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_withDensity_positive_rectangle_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_positive_rectangle_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_withDensity_axis_zero
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_axis_zero

#print axioms Papers.AnsariRockel2024.clayton_withDensity_positive_lowerOrthant_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_positive_lowerOrthant_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_withDensity_lowerOrthant_eq_measure
#assert_standard_axioms Papers.AnsariRockel2024.clayton_withDensity_lowerOrthant_eq_measure

#print axioms Papers.AnsariRockel2024.clayton_toMeasure_eq_withDensity_positive
#assert_standard_axioms Papers.AnsariRockel2024.clayton_toMeasure_eq_withDensity_positive

#print axioms Papers.AnsariRockel2024.clayton_positive_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_density_tp2

#print axioms Papers.AnsariRockel2024.clayton_positive_absolutelyContinuous
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_absolutelyContinuous

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_bounds
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_bounds

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_tendsto_one
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_square_tendsto_one

#print axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_cdf_bounds
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_positive_rectangle_cdf_bounds

#print axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_rectangle_tendsto_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_density_formula_cutoff_rectangle_tendsto_cdf

#print axioms Papers.AnsariRockel2024.clayton_negative_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_cdf
#print axioms Papers.AnsariRockel2024.clayton_positive_zero_axes
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_zero_axes
#print axioms Papers.AnsariRockel2024.clayton_negative_zero_axes
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_zero_axes
#print axioms Papers.AnsariRockel2024.clayton_one_cdf
#assert_standard_axioms Papers.AnsariRockel2024.clayton_one_cdf

#print axioms Papers.AnsariRockel2024.clayton_zero_ci_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_zero_ci_cd
#print axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_one_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one_cd

#print axioms Papers.AnsariRockel2024.clayton_negative_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_cd

#print axioms Papers.AnsariRockel2024.clayton_negative_nqd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_nqd

#print axioms Papers.AnsariRockel2024.clayton_positive_not_cd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_not_cd
#print axioms Papers.AnsariRockel2024.clayton_negative_not_ci
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_not_ci

#print axioms Papers.AnsariRockel2024.clayton_positive_ci
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_ci

#print axioms Papers.AnsariRockel2024.clayton_positive_pqd
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_pqd

#print axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_lower_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_upper_tail
#print axioms Papers.AnsariRockel2024.clayton_negative_one
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one
#print axioms Papers.AnsariRockel2024.clayton_tendsto_zero
#assert_standard_axioms Papers.AnsariRockel2024.clayton_tendsto_zero
#print axioms Papers.AnsariRockel2024.clayton_tendsto_atTop
#assert_standard_axioms Papers.AnsariRockel2024.clayton_tendsto_atTop

#print axioms Papers.AnsariRockel2024.classical_representation
#assert_standard_axioms Papers.AnsariRockel2024.classical_representation

#print axioms Papers.AnsariRockel2024.fgm_cdf
#assert_standard_axioms Papers.AnsariRockel2024.fgm_cdf

#print axioms Papers.AnsariRockel2024.xi_derivative_formula
#assert_standard_axioms Papers.AnsariRockel2024.xi_derivative_formula

#print axioms Papers.AnsariRockel2024.fgm_rho
#assert_standard_axioms Papers.AnsariRockel2024.fgm_rho

#print axioms Papers.AnsariRockel2024.fgm_tau
#assert_standard_axioms Papers.AnsariRockel2024.fgm_tau

#print axioms Papers.AnsariRockel2024.fgm_xi
#assert_standard_axioms Papers.AnsariRockel2024.fgm_xi

#print axioms Papers.AnsariRockel2024.frechet_rho
#assert_standard_axioms Papers.AnsariRockel2024.frechet_rho

#print axioms Papers.AnsariRockel2024.frechet_tau
#assert_standard_axioms Papers.AnsariRockel2024.frechet_tau

#print axioms Papers.AnsariRockel2024.frechet_xi
#assert_standard_axioms Papers.AnsariRockel2024.frechet_xi

#print axioms Papers.AnsariRockel2024.mardia_rho
#assert_standard_axioms Papers.AnsariRockel2024.mardia_rho

#print axioms Papers.AnsariRockel2024.mardia_tau
#assert_standard_axioms Papers.AnsariRockel2024.mardia_tau

#print axioms Papers.AnsariRockel2024.mardia_xi
#assert_standard_axioms Papers.AnsariRockel2024.mardia_xi

#print axioms Papers.AnsariRockel2024.fgm_ci
#assert_standard_axioms Papers.AnsariRockel2024.fgm_ci

#print axioms Papers.AnsariRockel2024.fgm_cd
#assert_standard_axioms Papers.AnsariRockel2024.fgm_cd

#print axioms Papers.AnsariRockel2024.fgm_lowerOrthant
#assert_standard_axioms Papers.AnsariRockel2024.fgm_lowerOrthant

#print axioms Papers.AnsariRockel2024.fgm_tails
#assert_standard_axioms Papers.AnsariRockel2024.fgm_tails

#print axioms Papers.AnsariRockel2024.frechet_tails
#assert_standard_axioms Papers.AnsariRockel2024.frechet_tails

#print axioms Papers.AnsariRockel2024.mardia_tails
#assert_standard_axioms Papers.AnsariRockel2024.mardia_tails

#print axioms Papers.AnsariRockel2024.fgm_density
#assert_standard_axioms Papers.AnsariRockel2024.fgm_density

#print axioms Papers.AnsariRockel2024.fgm_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.fgm_density_tp2_iff

#print axioms Papers.AnsariRockel2024.fgm_has_tp2_density
#assert_standard_axioms Papers.AnsariRockel2024.fgm_has_tp2_density

#print axioms Papers.AnsariRockel2024.nelsen7_cdf
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_cdf

#print axioms Papers.AnsariRockel2024.nelsen7_endpoints
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_endpoints

#print axioms Papers.AnsariRockel2024.nelsen7_cd
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_cd

#print axioms Papers.AnsariRockel2024.nelsen7_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.nelsen7_tails
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tails

#print axioms Papers.AnsariRockel2024.gumbel_tails
#assert_standard_axioms Papers.AnsariRockel2024.gumbel_tails

#print axioms Papers.AnsariRockel2024.marshallOlkin_tails
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_tails

#print axioms Papers.AnsariRockel2024.cuadrasAuge_tails
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_tails

#print axioms Papers.AnsariRockel2024.tawn_tails
#assert_standard_axioms Papers.AnsariRockel2024.tawn_tails

#print axioms Papers.AnsariRockel2024.fgm_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.fgm_schur_iff

#print axioms Papers.AnsariRockel2024.frechet_parameter_order
#assert_standard_axioms Papers.AnsariRockel2024.frechet_parameter_order

#print axioms Papers.AnsariRockel2024.frechet_order_counterexample
#assert_standard_axioms Papers.AnsariRockel2024.frechet_order_counterexample

#print axioms Papers.AnsariRockel2024.frechet_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_ci_iff

#print axioms Papers.AnsariRockel2024.frechet_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_cd_iff

#print axioms Papers.AnsariRockel2024.frechet_absolutelyContinuous_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_absolutelyContinuous_iff

#print axioms Papers.AnsariRockel2024.frechet_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.frechet_density_tp2_iff

#print axioms Papers.AnsariRockel2024.mardia_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_ci_iff

#print axioms Papers.AnsariRockel2024.mardia_cd_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_cd_iff

#print axioms Papers.AnsariRockel2024.mardia_absolutelyContinuous_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_absolutelyContinuous_iff

#print axioms Papers.AnsariRockel2024.mardia_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.mardia_density_tp2_iff

#print axioms Papers.AnsariRockel2024.mardia_not_lowerOrthant_ordered
#assert_standard_axioms Papers.AnsariRockel2024.mardia_not_lowerOrthant_ordered

#print axioms Papers.AnsariRockel2024.nelsen7_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_conditionalCDF

#print axioms Papers.AnsariRockel2024.nelsen7_derivative
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_derivative

#print axioms Papers.AnsariRockel2024.nelsen7_xi
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_xi

#print axioms Papers.AnsariRockel2024.nelsen7_ci_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_ci_iff

#print axioms Papers.AnsariRockel2024.nelsen7_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_schur_iff

#print axioms Papers.AnsariRockel2024.survival_lowerOrthant_iff
#assert_standard_axioms Papers.AnsariRockel2024.survival_lowerOrthant_iff

#print axioms Papers.AnsariRockel2024.survival_cis_iff
#assert_standard_axioms Papers.AnsariRockel2024.survival_cis_iff

#print axioms Papers.AnsariRockel2024.survival_schur_iff
#assert_standard_axioms Papers.AnsariRockel2024.survival_schur_iff

#print axioms Papers.AnsariRockel2024.concordance_coefficients_mono
#assert_standard_axioms Papers.AnsariRockel2024.concordance_coefficients_mono

#print axioms Papers.AnsariRockel2024.schur_xi_mono
#assert_standard_axioms Papers.AnsariRockel2024.schur_xi_mono

#print axioms Papers.AnsariRockel2024.lower_tail_mono
#assert_standard_axioms Papers.AnsariRockel2024.lower_tail_mono

#print axioms Papers.AnsariRockel2024.upper_tail_mono
#assert_standard_axioms Papers.AnsariRockel2024.upper_tail_mono

#print axioms Papers.AnsariRockel2024.schur_below_cis
#assert_standard_axioms Papers.AnsariRockel2024.schur_below_cis

#print axioms Papers.AnsariRockel2024.schur_below_cds
#assert_standard_axioms Papers.AnsariRockel2024.schur_below_cds

#print axioms Papers.AnsariRockel2024.cis_schur_iff_orthant
#assert_standard_axioms Papers.AnsariRockel2024.cis_schur_iff_orthant
#print axioms Papers.AnsariRockel2024.cds_schur_iff_reverse_orthant
#assert_standard_axioms Papers.AnsariRockel2024.cds_schur_iff_reverse_orthant

#print axioms Papers.AnsariRockel2024.extremeValue_schur_first_iff_pickands_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_first_iff_pickands_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_schur_second_iff_pickands_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_second_iff_pickands_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_tail_mono
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_tail_mono
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_concordance_mono
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_concordance_mono
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_xi_mono_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_xi_mono_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_schur_iff_pickands_of_ci
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_schur_iff_pickands_of_ci
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_order
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_order
#print axioms Papers.AnsariRockel2024.extremeValue_pickands_representation
#assert_standard_axioms Papers.AnsariRockel2024.extremeValue_pickands_representation
#print axioms Papers.AnsariRockel2024.marshallOlkin_rho
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_rho

#print axioms Papers.AnsariRockel2024.marshallOlkin_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_conditionalCDF

#print axioms Papers.AnsariRockel2024.marshallOlkin_xi
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_xi

#print axioms Papers.AnsariRockel2024.marshallOlkin_tau
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_tau

#print axioms Papers.AnsariRockel2024.marshallOlkin_cdf
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_cdf
#print axioms Papers.AnsariRockel2024.marshallOlkin_ci
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_ci
#print axioms Papers.AnsariRockel2024.marshallOlkin_orthant_mono
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_orthant_mono
#print axioms Papers.AnsariRockel2024.marshallOlkin_schur_mono
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_schur_mono
#print axioms Papers.AnsariRockel2024.cuadrasAuge_ci
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_ci
#print axioms Papers.AnsariRockel2024.cuadrasAuge_orthant_mono
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_orthant_mono
#print axioms Papers.AnsariRockel2024.cuadrasAuge_schur_mono
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_schur_mono

#print axioms Papers.AnsariRockel2024.cuadrasAuge_conditionalCDF
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_conditionalCDF
#print axioms Papers.AnsariRockel2024.cuadrasAuge_rho
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_rho
#print axioms Papers.AnsariRockel2024.cuadrasAuge_xi
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_xi

#print axioms Papers.AnsariRockel2024.cuadrasAuge_tau
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_tau

#print axioms Papers.AnsariRockel2024.marshallOlkin_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_density_tp2
#print axioms Papers.AnsariRockel2024.marshallOlkin_absolutelyContinuous
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_absolutelyContinuous
#print axioms Papers.AnsariRockel2024.marshallOlkin_independence_axes
#assert_standard_axioms Papers.AnsariRockel2024.marshallOlkin_independence_axes
#print axioms Papers.AnsariRockel2024.cuadrasAuge_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_density_tp2
#print axioms Papers.AnsariRockel2024.cuadrasAuge_absolutelyContinuous
#assert_standard_axioms Papers.AnsariRockel2024.cuadrasAuge_absolutelyContinuous

#print axioms Papers.AnsariRockel2024.clayton_positive_cdf_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_positive_cdf_tp2
#print axioms Papers.AnsariRockel2024.clayton_zero_cdf_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_zero_cdf_tp2
#print axioms Papers.AnsariRockel2024.clayton_negative_not_cdf_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_not_cdf_tp2

#print axioms Papers.AnsariRockel2024.clayton_negative_one_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_one_not_density_tp2

#print axioms Papers.AnsariRockel2024.hasMTP2Density_isPQD
#assert_standard_axioms Papers.AnsariRockel2024.hasMTP2Density_isPQD

#print axioms Papers.AnsariRockel2024.clayton_negative_not_density_tp2
#assert_standard_axioms Papers.AnsariRockel2024.clayton_negative_not_density_tp2

#print axioms Papers.AnsariRockel2024.isCD_eq_independence_of_hasMTP2Density
#assert_standard_axioms Papers.AnsariRockel2024.isCD_eq_independence_of_hasMTP2Density

#print axioms Papers.AnsariRockel2024.isCD_eq_independence_of_isTP2CDF
#assert_standard_axioms Papers.AnsariRockel2024.isCD_eq_independence_of_isTP2CDF

#print axioms Papers.AnsariRockel2024.nelsen7_cdf_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_cdf_tp2_iff

#print axioms Papers.AnsariRockel2024.nelsen7_density_tp2_iff
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_density_tp2_iff

#print axioms Papers.AnsariRockel2024.fgm_hasMTP2Density_iff
#assert_standard_axioms Papers.AnsariRockel2024.fgm_hasMTP2Density_iff

#print axioms Papers.AnsariRockel2024.nelsen7_integral_cdf_first
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_integral_cdf_first
#print axioms Papers.AnsariRockel2024.nelsen7_rho_integral
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_rho_integral
#print axioms Papers.AnsariRockel2024.nelsen7_rho_interior
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_rho_interior
#print axioms Papers.AnsariRockel2024.nelsen7_rho
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_rho
#print axioms Papers.AnsariRockel2024.nelsen7_tau_rho
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tau_rho
#print axioms Papers.AnsariRockel2024.nelsen7_tau_interior
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tau_interior
#print axioms Papers.AnsariRockel2024.nelsen7_tau
#assert_standard_axioms Papers.AnsariRockel2024.nelsen7_tau
