import Papers.AnsariRockel2024.GumbelBarnett
import Papers.AnsariRockel2024.ClaytonDensityDerivative
import Papers.AnsariRockel2024.DensityTP2Consequences
import Papers.AnsariRockel2024.CuadrasAugeResults
import Papers.AnsariRockel2024.ExtremeValueOrders
import Papers.AnsariRockel2024.NamedExtremeValueCDF
import Papers.AnsariRockel2024.GumbelLimits
import Papers.AnsariRockel2024.GumbelOrder
import Papers.AnsariRockel2024.JoeLimits
import Papers.AnsariRockel2024.NamedArchimedeanCDF
import Papers.AnsariRockel2024.GeneralOrders
import Papers.AnsariRockel2024.Nelsen7Results
import Papers.AnsariRockel2024.Nelsen2Dependence
import Papers.AnsariRockel2024.Nelsen2Limits
import Papers.AnsariRockel2024.Nelsen8Dependence
import Papers.AnsariRockel2024.Nelsen8Limits
import Papers.AnsariRockel2024.Nelsen12Limits
import Papers.AnsariRockel2024.Nelsen12Order
import Papers.AnsariRockel2024.Nelsen12Tails
import Papers.AnsariRockel2024.Nelsen14Tails
import Papers.AnsariRockel2024.GenestGhoudiTails
import Papers.AnsariRockel2024.GenestGhoudiDependence
import Papers.AnsariRockel2024.PowerFamilyLimits

import Papers.AnsariRockel2024.NelsenEndpointDependence

import Papers.AnsariRockel2024.CDFTotalPositivity
import Papers.AnsariRockel2024.AMHTotalPositivity
import Papers.AnsariRockel2024.AMHSchur
import Papers.AnsariRockel2024.Nelsen7Rho
import Papers.AnsariRockel2024.Nelsen7Tau
import Papers.AnsariRockel2024.Nelsen7SourceCorrection
import Papers.AnsariRockel2024.FrechetMardiaDependence
import Papers.AnsariRockel2024.TailsAndOrders
import Papers.AnsariRockel2024.FamilyExtensions
import Papers.AnsariRockel2024.Association
import Papers.AnsariRockel2024.Dependence
import Papers.AnsariRockel2024.FrankTails
import Papers.AnsariRockel2024.FrankDependence
import Papers.AnsariRockel2024.FrankDensity
import Papers.AnsariRockel2024.FrankLimits
import Papers.AnsariRockel2024.FrankContinuity
import Papers.AnsariRockel2024.Nelsen10
import Papers.AnsariRockel2024.Nelsen11
import Papers.AnsariRockel2024.Nelsen13
import Papers.AnsariRockel2024.NelsenPowerConditional

/-!
# AnsariRockel2024: public results

Selected FGM, Fréchet and Mardia results from Tables 5 and 6 are checked here.
The exact correspondence, conventions, and remaining gaps are in `COVERAGE.md`.
-/
