"""Import every project module so doc-gen4 includes even non-entrypoint files."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    modules = {"Papers", "Verification"}
    for directory in ("Papers", "Verification"):
        modules.update(
            ".".join(path.relative_to(ROOT).with_suffix("").parts)
            for path in (ROOT / directory).rglob("*.lean")
        )
    target = ROOT / "docbuild" / "Handbook.lean"
    target.write_text(
        "-- Generated by scripts/prepare_docs.py; do not edit.\n"
        + "\n".join(f"import {module}" for module in sorted(modules))
        + "\n",
        encoding="utf-8",
    )
    print(f"Prepared doc-gen4 imports for {len(modules)} modules.")


if __name__ == "__main__":
    main()
