import Papers.Rockel2025Approximation.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.Rockel2025Approximation.dyadicBlocks_cdf
#assert_standard_axioms Papers.Rockel2025Approximation.dyadicBlocks_cdf

#print axioms Papers.Rockel2025Approximation.dyadicBlocks_rho
#assert_standard_axioms Papers.Rockel2025Approximation.dyadicBlocks_rho

#print axioms Papers.Rockel2025Approximation.dyadicBlocks_tau
#assert_standard_axioms Papers.Rockel2025Approximation.dyadicBlocks_tau

#print axioms Papers.Rockel2025Approximation.checkerboard_rho_tau
#assert_standard_axioms Papers.Rockel2025Approximation.checkerboard_rho_tau

#print axioms Papers.Rockel2025Approximation.checkMin_corrections
#assert_standard_axioms Papers.Rockel2025Approximation.checkMin_corrections

#print axioms Papers.Rockel2025Approximation.checkW_corrections
#assert_standard_axioms Papers.Rockel2025Approximation.checkW_corrections

#print axioms Papers.Rockel2025Approximation.equalGrid_cdf
#assert_standard_axioms Papers.Rockel2025Approximation.equalGrid_cdf

#print axioms Papers.Rockel2025Approximation.equalGrid_rho_tau
#assert_standard_axioms Papers.Rockel2025Approximation.equalGrid_rho_tau

#print axioms Papers.Rockel2025Approximation.equal_checkerboard_rho_tau
#assert_standard_axioms Papers.Rockel2025Approximation.equal_checkerboard_rho_tau

#print axioms Papers.Rockel2025Approximation.equal_checkMin_coefficients
#assert_standard_axioms Papers.Rockel2025Approximation.equal_checkMin_coefficients

#print axioms Papers.Rockel2025Approximation.equal_checkW_coefficients
#assert_standard_axioms Papers.Rockel2025Approximation.equal_checkW_coefficients

#print axioms Papers.Rockel2025Approximation.equal_checkerboard_tails
#assert_standard_axioms Papers.Rockel2025Approximation.equal_checkerboard_tails

#print axioms Papers.Rockel2025Approximation.equal_checkMin_tails
#assert_standard_axioms Papers.Rockel2025Approximation.equal_checkMin_tails

#print axioms Papers.Rockel2025Approximation.equal_checkW_tails
#assert_standard_axioms Papers.Rockel2025Approximation.equal_checkW_tails

#print axioms Papers.Rockel2025Approximation.permutationShuffle_cdf
#assert_standard_axioms Papers.Rockel2025Approximation.permutationShuffle_cdf

#print axioms Papers.Rockel2025Approximation.permutationShuffle_rho
#assert_standard_axioms Papers.Rockel2025Approximation.permutationShuffle_rho

#print axioms Papers.Rockel2025Approximation.permutationShuffle_tau
#assert_standard_axioms Papers.Rockel2025Approximation.permutationShuffle_tau

#print axioms Papers.Rockel2025Approximation.permutationShuffle_xi
#assert_standard_axioms Papers.Rockel2025Approximation.permutationShuffle_xi

#print axioms Papers.Rockel2025Approximation.permutationShuffle_lower_tail
#assert_standard_axioms Papers.Rockel2025Approximation.permutationShuffle_lower_tail

#print axioms Papers.Rockel2025Approximation.permutationShuffle_upper_tail
#assert_standard_axioms Papers.Rockel2025Approximation.permutationShuffle_upper_tail

#print axioms Papers.Rockel2025Approximation.bernstein_cdf
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_cdf

#print axioms Papers.Rockel2025Approximation.bernstein_uniform_error
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_uniform_error

#print axioms Papers.Rockel2025Approximation.bernstein_uniform_convergence
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_uniform_convergence

#print axioms Papers.Rockel2025Approximation.rectangular_checkerboard_cdf
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkerboard_cdf

#print axioms Papers.Rockel2025Approximation.rectangular_checkMin_cdf
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkMin_cdf

#print axioms Papers.Rockel2025Approximation.rectangular_checkW_cdf
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkW_cdf

#print axioms Papers.Rockel2025Approximation.patchwork_grid_interpolation
#assert_standard_axioms Papers.Rockel2025Approximation.patchwork_grid_interpolation

#print axioms Papers.Rockel2025Approximation.patchwork_uniform_convergence
#assert_standard_axioms Papers.Rockel2025Approximation.patchwork_uniform_convergence

#print axioms Papers.Rockel2025Approximation.bernstein_rho_grid
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_rho_grid

#print axioms Papers.Rockel2025Approximation.bernstein_rho_frobenius
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_rho_frobenius

#print axioms Papers.Rockel2025Approximation.bernstein_basis_integral
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_basis_integral

#print axioms Papers.Rockel2025Approximation.bernstein_lambda_entry
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_lambda_entry

#print axioms Papers.Rockel2025Approximation.bernstein_upsilon_entry
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_upsilon_entry

#print axioms Papers.Rockel2025Approximation.bernstein_conditional_cdf
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_conditional_cdf

#print axioms Papers.Rockel2025Approximation.bernstein_xi_finite_sum
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_xi_finite_sum

#print axioms Papers.Rockel2025Approximation.bernstein_lower_tail
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_lower_tail

#print axioms Papers.Rockel2025Approximation.bernstein_upper_tail
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_upper_tail

#print axioms Papers.Rockel2025Approximation.bernstein_density_nonnegative
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_density_nonnegative

#print axioms Papers.Rockel2025Approximation.bernstein_density
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_density

#print axioms Papers.Rockel2025Approximation.bernstein_kernel_monotone
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_kernel_monotone

#print axioms Papers.Rockel2025Approximation.bernstein_theta_integral
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_theta_integral

#print axioms Papers.Rockel2025Approximation.bernstein_tau_finite_sum
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_tau_finite_sum

#print axioms Papers.Rockel2025Approximation.bernstein_tau_trace
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_tau_trace

#print axioms Papers.Rockel2025Approximation.bernstein_upsilon_matrix
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_upsilon_matrix

#print axioms Papers.Rockel2025Approximation.bernstein_lambda_matrix
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_lambda_matrix

#print axioms Papers.Rockel2025Approximation.bernstein_xi_trace
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_xi_trace

#print axioms Papers.Rockel2025Approximation.bernstein_all_coefficients
#assert_standard_axioms Papers.Rockel2025Approximation.bernstein_all_coefficients

#print axioms Papers.Rockel2025Approximation.rectangular_checkerboard_rho
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkerboard_rho

#print axioms Papers.Rockel2025Approximation.rectangular_checkMin_rho
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkMin_rho

#print axioms Papers.Rockel2025Approximation.rectangular_checkW_rho
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkW_rho

#print axioms Papers.Rockel2025Approximation.rectangular_checkerboard_tau
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkerboard_tau

#print axioms Papers.Rockel2025Approximation.rectangular_checkMin_tau
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkMin_tau

#print axioms Papers.Rockel2025Approximation.rectangular_checkW_tau
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkW_tau

#print axioms Papers.Rockel2025Approximation.patchwork_rho_correction
#assert_standard_axioms Papers.Rockel2025Approximation.patchwork_rho_correction

#print axioms Papers.Rockel2025Approximation.patchwork_tau_correction
#assert_standard_axioms Papers.Rockel2025Approximation.patchwork_tau_correction

#print axioms Papers.Rockel2025Approximation.patchwork_conditionalCDF
#assert_standard_axioms Papers.Rockel2025Approximation.patchwork_conditionalCDF

#print axioms Papers.Rockel2025Approximation.patchwork_xi_formula
#assert_standard_axioms Papers.Rockel2025Approximation.patchwork_xi_formula

#print axioms Papers.Rockel2025Approximation.patchwork_xi_correction
#assert_standard_axioms Papers.Rockel2025Approximation.patchwork_xi_correction

#print axioms Papers.Rockel2025Approximation.rectangular_checkerboard_xi
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkerboard_xi

#print axioms Papers.Rockel2025Approximation.uniform_patchwork_xi_correction
#assert_standard_axioms Papers.Rockel2025Approximation.uniform_patchwork_xi_correction

#print axioms Papers.Rockel2025Approximation.rectangular_perfect_xi
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_perfect_xi

#print axioms Papers.Rockel2025Approximation.rectangular_checkMin_xi
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkMin_xi

#print axioms Papers.Rockel2025Approximation.rectangular_checkW_xi
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkW_xi

#print axioms Papers.Rockel2025Approximation.rectangular_xi_error_bound
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_xi_error_bound

#print axioms Papers.Rockel2025Approximation.rectangular_checkerboard_lower_tail
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkerboard_lower_tail

#print axioms Papers.Rockel2025Approximation.rectangular_checkerboard_upper_tail
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkerboard_upper_tail

#print axioms Papers.Rockel2025Approximation.rectangular_checkMin_lower_tail
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkMin_lower_tail

#print axioms Papers.Rockel2025Approximation.rectangular_checkMin_upper_tail
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkMin_upper_tail

#print axioms Papers.Rockel2025Approximation.rectangular_checkW_lower_tail
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkW_lower_tail

#print axioms Papers.Rockel2025Approximation.rectangular_checkW_upper_tail
#assert_standard_axioms Papers.Rockel2025Approximation.rectangular_checkW_upper_tail

#print axioms Papers.Rockel2025Approximation.checkerboardEstimator_eq_average
#assert_standard_axioms Papers.Rockel2025Approximation.checkerboardEstimator_eq_average

#print axioms Papers.Rockel2025Approximation.checkerboardEstimator_mem
#assert_standard_axioms Papers.Rockel2025Approximation.checkerboardEstimator_mem

#print axioms Papers.Rockel2025Approximation.checkerboardEstimator_correction_bounds
#assert_standard_axioms Papers.Rockel2025Approximation.checkerboardEstimator_correction_bounds

#print axioms Papers.Rockel2025Approximation.checkerboardEstimator_correction_tendsto
#assert_standard_axioms Papers.Rockel2025Approximation.checkerboardEstimator_correction_tendsto

#print axioms Papers.Rockel2025Approximation.checkerboardEstimator_tendsto_iff
#assert_standard_axioms Papers.Rockel2025Approximation.checkerboardEstimator_tendsto_iff

#print axioms Papers.Rockel2025Approximation.majorization_sum_sq
#assert_standard_axioms Papers.Rockel2025Approximation.majorization_sum_sq

#print axioms Papers.Rockel2025Approximation.mtp2_isCI
#assert_standard_axioms Papers.Rockel2025Approximation.mtp2_isCI

#print axioms Papers.Rockel2025Approximation.checkerboard_xi_le_of_isCI
#assert_standard_axioms Papers.Rockel2025Approximation.checkerboard_xi_le_of_isCI

#print axioms Papers.Rockel2025Approximation.checkerboard_xi_le_of_mtp2
#assert_standard_axioms Papers.Rockel2025Approximation.checkerboard_xi_le_of_mtp2
