import Papers.Rockel2025Approximation.Main
import Verification.AxiomAudit

/-! Transitive axiom reports and enforced standard-foundation checks. -/

#print axioms Papers.Rockel2025Approximation.dyadicBlocks_cdf
#assert_standard_axioms Papers.Rockel2025Approximation.dyadicBlocks_cdf

#print axioms Papers.Rockel2025Approximation.dyadicBlocks_rho
#assert_standard_axioms Papers.Rockel2025Approximation.dyadicBlocks_rho

#print axioms Papers.Rockel2025Approximation.dyadicBlocks_tau
#assert_standard_axioms Papers.Rockel2025Approximation.dyadicBlocks_tau

#print axioms Papers.Rockel2025Approximation.checkerboard_rho_tau
#assert_standard_axioms Papers.Rockel2025Approximation.checkerboard_rho_tau

#print axioms Papers.Rockel2025Approximation.checkMin_corrections
#assert_standard_axioms Papers.Rockel2025Approximation.checkMin_corrections

#print axioms Papers.Rockel2025Approximation.checkW_corrections
#assert_standard_axioms Papers.Rockel2025Approximation.checkW_corrections
