import Papers.Rockel2025Approximation.Counterexamples
import Papers.Rockel2025Approximation.StatisticalConsistency
import Papers.Rockel2025Approximation.PopulationConvergence
import Papers.Rockel2025Approximation.CheckerboardMTP2
import Papers.Rockel2025Approximation.ConvergenceSteps
import Papers.Rockel2025Approximation.RectangularTails
import Papers.Rockel2025Approximation.RectangularXi
import Papers.Rockel2025Approximation.RectangularRanks
import Papers.Rockel2025Approximation.BernsteinExact
import Papers.Rockel2025Approximation.BernsteinKendall
import Papers.Rockel2025Approximation.BernsteinRank
import Papers.Rockel2025Approximation.Constructors
import Papers.Rockel2025Approximation.PermutationShuffles
import Papers.Rockel2025Approximation.EqualGrids
import Papers.Rockel2025Approximation.DyadicBlocks

/-! # Rockel2025Approximation: public results

See `COVERAGE.md` for the exact verified subset and remaining obligations.
-/
